import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import {auditDataset,searchEvidence} from '../worker/quality.js';
import {newRun,stepRun,validDate} from '../worker/engine.js';
import {collectAnnouncements,readPublic} from '../worker/collector.js';
import {cachedSupport} from '../worker/daily.js';
import {aiDecision,allocateScores,validateDecision} from '../worker/model.js';
import {extractFiling} from '../runtime/filings.mjs';
import worker from '../dist/server/index.js';
import {newsMonths} from '../worker/backfill.js';

function db(){const sql=new DatabaseSync(':memory:');for(const file of fs.readdirSync('drizzle').filter(x=>x.endsWith('.sql')))sql.exec(fs.readFileSync('drizzle/'+file,'utf8').replaceAll('--> statement-breakpoint',''));const make=(query,args=[])=>({bind(...next){return make(query,next)},first(){return sql.prepare(query).get(...args)||null},all(){return {results:sql.prepare(query).all(...args)}},run(){return {meta:{changes:Number(sql.prepare(query).run(...args).changes)}}}});return {prepare:query=>make(query),batch(items){sql.exec('BEGIN');try{const results=items.map(x=>x.run());sql.exec('COMMIT');return results;}catch(error){sql.exec('ROLLBACK');throw error;}},close:()=>sql.close()};}
function fixture(){return {start:'2026-09-01',end:'2026-09-04',synthetic:true,stocks:['600519','600036'].map(code=>({code,name:'SYNTHETIC '+code,bars:['2026-08-31','2026-09-01','2026-09-02','2026-09-03','2026-09-04'].map(date=>({date,open:10,high:10,low:10,close:10,volume:1000})),ruleEvidence:[]})),documents:[{id:'past',code:'600519',title:'Test growth',url:'https://example.invalid/past',availableAt:'2026-09-01T10:00:00+08:00',kind:'公司公告'},{id:'future',code:'600036',title:'Future record',url:'https://example.invalid/future',availableAt:'2026-09-03T10:00:00+08:00',kind:'财经新闻'}],dailySupport:{calendar:['2026-09-01','2026-09-02','2026-09-03','2026-09-04'].map(date=>({date,isOpen:true,exchanges:['SSE','SZSE']}))},sources:[],coverage:[],corporateActions:[],warnings:['SYNTHETIC TEST ONLY']};}

test('quality uses dated calendar, reports missing stock/day and does not claim complete news',()=>{const d=fixture();d.requestedCodes=['600519','600036','601318'];d.stocks[0].bars=d.stocks[0].bars.filter(b=>b.date!=='2026-09-02');const q=auditDataset(d);assert.deepEqual(q.missingStocks,['601318']);assert.deepEqual(q.stocks[0].missingDates,['2026-09-02']);assert.equal(q.stocks[0].priceCoverage,.75);assert.equal(q.pricesCovered,false);assert.equal(q.newsArchiveComplete,false);assert.equal(q.strictReady,false);});
test('unknown calendar stays unknown instead of measuring bars against themselves',()=>{const d=fixture();delete d.dailySupport;assert.equal(auditDataset(d).stocks[0].expectedTradingDays,null);assert.equal(auditDataset(d).stocks[0].priceCoverage,null);});
test('local search never releases future documents/prices or accepts out-of-pool codes',()=>{const d=fixture(),r=searchEvidence(d,'2026-09-01');assert.deepEqual(r.documents.map(x=>x.id),['past']);assert.ok(r.prices.every(s=>s.bars.every(b=>b.date<='2026-09-01')));assert.throws(()=>searchEvidence(d,'2026-09-01',{codes:['000001']}));});
test('round-robin retrieval retains sparsely covered stock',()=>{const d=fixture();d.documents.push({...d.documents[0],id:'other',code:'600036'});for(let i=0;i<30;i++)d.documents.push({...d.documents[0],id:'many-'+i});assert.ok(searchEvidence(d,'2026-09-01',{limit:2}).documents.some(x=>x.code==='600036'));});
test('research rules require explicit acknowledgment and preserve strict blocking',()=>{const d=fixture();assert.equal(stepRun(newRun(d,{}),d).status,'blocked');assert.throws(()=>newRun(d,{ruleMode:'research_assumptions'}),/明确确认/);const r=stepRun(newRun(d,{ruleMode:'research_assumptions',acknowledgeUnverifiedRules:true}),d);assert.equal(r.status,'running');assert.equal(d.stocks[0].ruleEvidence.length,0);assert.ok(r.warnings.some(x=>x.includes('研究假设')));});
test('price-only mode does not book dividends or pretend to verify corporate actions',()=>{const d=fixture();d.corporateActions=[{code:'600519',recordDate:'2026-09-01',exDate:'2026-09-02',payDate:'2026-09-03',cashPerShare:.1,sourceUrl:'https://example.invalid/dividend'}];let r=newRun(d,{ruleMode:'research_assumptions',acknowledgeUnverifiedRules:true,corporateActionMode:'price_only'});for(let i=0;i<4;i++)r=stepRun(r,d);assert.equal(r.dividendIncome,0);assert.equal(r.paidDividends.length,0);});
test('invalid calendar strings return false without RangeError',()=>{assert.equal(validDate('2026-99-99'),false);assert.equal(validDate('2026-02-30'),false);});
test('announcement crawler follows pages, deduplicates IDs and records remaining coverage',async()=>{let calls=0;const reader=async(url,options)=>{calls++;const page=new URLSearchParams(options.body).get('pageNum');return {json:{hasMore:page==='1',totalAnnouncement:2,announcements:[{secCode:'600519',announcementTime:Date.parse('2026-09-01'),announcementId:page,announcementTitle:'SYNTHETIC '+page,adjunctUrl:'finalpage/2026-09-01/'+page+'.PDF'}]},provenance:{url,sha256:'test',fetchedAt:'2026-10-08'}};};const r=await collectAnnouncements({code:'600519',exchange:'SSE',orgId:'test'},'2026-09-01','2026-09-04',{reader,wait:async()=>{}});assert.equal(calls,2);assert.equal(r.documents.length,2);assert.equal(r.coverage.queryExhausted,true);const limited=await collectAnnouncements({code:'600519',exchange:'SSE',orgId:'test'},'2026-09-01','2026-09-04',{maxPages:1,reader,wait:async()=>{}});assert.equal(limited.coverage.complete,false);assert.equal(limited.coverage.nextPage,2);});
test('failed cached source expires and succeeds on a later request',async()=>{const DB=db();try{DB.prepare('INSERT INTO settings VALUES(?,?)').bind('daily:test',JSON.stringify({unavailable:'temporary',_cachedAt:'2020-01-01T00:00:00Z'})).run();let count=0;const r=await cachedSupport(DB,'test',async()=>{count++;return {records:[1]}});assert.equal(count,1);assert.deepEqual(r.records,[1]);await cachedSupport(DB,'test',async()=>{count++;return {}});assert.equal(count,1);}finally{DB.close();}});
test('AI can plan a local search and cite only returned cutoff-valid evidence',async()=>{const DB=db(),d=fixture();const state=stepRun(newRun(d,{ruleMode:'research_assumptions',acknowledgeUnverifiedRules:true,retrievalMode:'ai_search'}),d);let calls=0;try{const result=await aiDecision({SILICONFLOW_API_KEY:'TEST_ONLY_KEY'},DB,'run',0,state,d,'2026-09-01',{provider:'siliconflow',model:'Qwen/Qwen3-8B',maxBudget:0},async(url,options)=>{calls++;const value=calls===1?{queries:[{query:'test',codes:['600519']}]}:{weights:{'600519':.5,'600036':.5},reason:'synthetic decision',evidenceIds:['past']};if(calls===2){const packet=JSON.parse(JSON.parse(options.body).messages[1].content);assert.ok(!packet.documents.some(x=>x.id==='future'));assert.equal(packet.retrieval.missingNewsCodes[0],'600036');}return Response.json({model:'test',choices:[{finish_reason:'stop',message:{content:JSON.stringify(value)}}],usage:{prompt_tokens:10,completion_tokens:5,total_tokens:15}});});assert.equal(calls,2);assert.equal(result.requests,2);assert.equal(result.usage.total_tokens,30);assert.ok(result.retrieval.queries.some(x=>x.plannedBy==='platform_coverage_guard'));const again=await aiDecision({SILICONFLOW_API_KEY:'TEST_ONLY_KEY'},DB,'run',0,state,d,'2026-09-01',{provider:'siliconflow',model:'Qwen/Qwen3-8B',maxBudget:0},async()=>{throw Error('must not repeat')});assert.deepEqual(again,result);}finally{DB.close();}});
test('API reports configured model consistently and versions match exports',async()=>{const DB=db();try{DB.prepare('INSERT INTO settings VALUES(?,?)').bind('model',JSON.stringify({provider:'siliconflow',model:'Qwen/Qwen3-8B',maxBudget:0,inputPrice:0,outputPrice:0})).run();const env={DB,SILICONFLOW_API_KEY:'TEST_ONLY_KEY'};const status=await(await worker.fetch(new Request('https://local.test/api/status'),env)).json();assert.equal(status.ai.configured,true);assert.equal(status.engineVersion,'2.1.0');}finally{DB.close();}});
test('filing extractor rejects arbitrary URLs before any network access',async()=>{let calls=0;await assert.rejects(extractFiling('https://example.com/a.pdf',{fetchImpl:async()=>{calls++;}}));assert.equal(calls,0);});
test('monthly backfill includes partial first/last month and crosses year boundary',()=>{assert.deepEqual(newsMonths('2025-12-28','2026-02-03'),[{start:'2025-12-28',end:'2025-12-31'},{start:'2026-01-01',end:'2026-01-31'},{start:'2026-02-01',end:'2026-02-03'}]);assert.equal(newsMonths('2026-04-01','2026-09-30').length,6);});
test('announcement later-page error preserves successful earlier pages and exposes remaining cursor',async()=>{let calls=0;const result=await collectAnnouncements({code:'600519',exchange:'SSE',orgId:'test'},'2026-09-01','2026-09-04',{wait:async()=>{},reader:async(url)=>{if(++calls===2)throw Error('HTTP 504');return {json:{hasMore:true,announcements:[{secCode:'600519',announcementTime:Date.parse('2026-09-01'),announcementId:'one',announcementTitle:'TEST',adjunctUrl:'finalpage/2026-09-01/1.PDF'}]},provenance:{url}};}});assert.equal(result.documents.length,1);assert.equal(result.coverage.complete,false);assert.equal(result.coverage.nextPage,2);assert.match(result.coverage.error,/504/);});
test('durable monthly news task preserves original data and control does not invalidate an in-flight batch',async()=>{const DB=db(),d=fixture();try{DB.prepare('INSERT INTO datasets VALUES(?,?,?)').bind('base','now',JSON.stringify(d)).run();for(const stock of d.stocks){const query={keyword:stock.name,companyCode:stock.code,start:d.start,end:d.end,offset:0};const observed=new Date().toISOString();DB.prepare('INSERT INTO settings VALUES(?,?)').bind('daily:company-news:'+JSON.stringify(query)+':'+observed.slice(0,10),JSON.stringify({_cachedAt:observed,documents:[{id:'news-'+stock.code,code:null,title:'Synthetic news '+stock.code,url:'https://example.invalid/'+stock.code,publicationDate:'2026-09-02',availableAt:observed,firstObservedAt:observed,availabilityBasis:'observed_only',association:{requestedCompanyCode:stock.code},kind:'财经新闻'}],provenance:[{url:'https://example.invalid/search',sha256:'test'}],coverage:{nextOffset:null,sourceReportedTotal:1}})).run();}const call=async(url,body)=>{const response=await worker.fetch(new Request('https://local.test/api/'+url,{method:'POST',body:JSON.stringify(body)}),{DB});const value=await response.json();assert.equal(response.status,200,JSON.stringify(value));return value;};let job=await call('news-backfill',{datasetId:'base',background:false});assert.equal(job.total,2);const before=job.version;job=await call('collection-jobs/'+job.id+'/control',{action:'resume'});assert.equal(job.version,before);job=await call('collection-jobs/'+job.id+'/control',{action:'pause'});assert.equal(job.background,false);for(let i=0;i<2;i++)job=await call('collection-jobs/'+job.id+'/step',{expectedVersion:job.version});assert.equal(job.status,'completed');const copy=JSON.parse(DB.prepare('SELECT payload FROM datasets WHERE id=?').bind(job.datasetId).first().payload);assert.equal(copy.documents.length,d.documents.length+2);assert.equal(JSON.parse(DB.prepare('SELECT payload FROM datasets WHERE id=?').bind('base').first().payload).documents.length,d.documents.length);}finally{DB.close();}});

test('12-stock relative scores produce a bounded budget instead of 12 times ten percent',()=>{const codes=Array.from({length:12},(_,i)=>String(600000+i)),scores=Object.fromEntries(codes.map(c=>[c,10]));const result=allocateScores({allocationScores:scores,investedFraction:.9,reason:'test',evidenceIds:[]},codes);const validated=validateDecision(result.value,codes,[]);assert.ok(Math.abs(Object.values(validated.weights).reduce((a,b)=>a+b,0)-.9)<1e-9);assert.ok(Object.values(validated.weights).every(w=>Math.abs(w-.075)<1e-9));assert.deepEqual(result.allocationPlan.scores,scores);assert.throws(()=>allocateScores({allocationScores:scores,investedFraction:1.2},codes));assert.throws(()=>allocateScores({allocationScores:{...scores,'999999':1},investedFraction:1},codes));});
test('relative allocation preserves frozen positions and permits a cash-only signal',()=>{const codes=['600519','600036'];const frozen=[{code:'600519',tradable:false,frozenWeight:.3}];const result=allocateScores({allocationScores:{'600519':100,'600036':10},investedFraction:.8,reason:'test',evidenceIds:[]},codes,frozen);assert.deepEqual(validateDecision(result.value,codes,[],frozen).weights,{'600519':.3,'600036':.5});const cash=allocateScores({allocationScores:{'600519':0,'600036':0},investedFraction:0,reason:'cash',evidenceIds:[]},codes);assert.deepEqual(cash.value.weights,{'600519':0,'600036':0});});
test('AI validation failure records a safe specific cause and cannot be silently retried',async()=>{const DB=db(),d=fixture(),state=newRun(d,{});let calls=0;try{await assert.rejects(aiDecision({SILICONFLOW_API_KEY:'TEST_ONLY_KEY'},DB,'bad',0,state,d,'2026-09-01',{provider:'siliconflow',model:'Qwen/Qwen3-8B',maxBudget:0},async()=>{calls++;return Response.json({choices:[{finish_reason:'stop',message:{content:JSON.stringify({weights:{'600519':.8,'600036':.8},reason:'test',evidenceIds:[]})}}]});}),/权重之和/);const attempt=DB.prepare('SELECT * FROM model_attempts WHERE id=?').bind('bad:0').first();assert.equal(attempt.status,'uncertain');const payload=JSON.parse(attempt.payload);assert.equal(payload.stage,'validation');assert.equal(payload.errorCode,'模型权重之和超过 100%');assert.ok(!attempt.payload.includes('TEST_ONLY_KEY'));await assert.rejects(aiDecision({SILICONFLOW_API_KEY:'TEST_ONLY_KEY'},DB,'bad',0,state,d,'2026-09-01',{provider:'siliconflow',model:'Qwen/Qwen3-8B',maxBudget:0},async()=>{calls++;}),/停止重试/);assert.equal(calls,1);}finally{DB.close();}});


test('public source size limit stops an oversized streaming response before reading it all',async()=>{const original=globalThis.fetch;let reads=0,cancelled=false;globalThis.fetch=async()=>new Response(new ReadableStream({pull(controller){reads++;controller.enqueue(new Uint8Array(1100000));},cancel(){cancelled=true;}}));try{await assert.rejects(readPublic('https://example.invalid/test'),/大小限制/);assert.equal(cancelled,true);assert.ok(reads<=4);}finally{globalThis.fetch=original;}});


test('model config save and status agree and do not mark unpaid unpriced providers ready',async()=>{const DB=db(),env={DB,SILICONFLOW_API_KEY:'TEST_ONLY_KEY',OPENAI_API_KEY:'TEST_ONLY_KEY'};const call=async(url,body)=>await(await worker.fetch(new Request('https://local.test/api/'+url,body?{method:'POST',body:JSON.stringify(body)}:{}),env)).json();try{const free={provider:'siliconflow',model:'Qwen/Qwen3-8B',maxBudget:0,inputPrice:0,outputPrice:0};assert.equal((await call('model-config',free)).configured,true);assert.equal((await call('model-config')).configured,true);assert.equal((await call('status')).ai.configured,true);await call('model-config',{...free,provider:'openai',model:'test-unpriced'});assert.equal((await call('model-config')).configured,false);assert.equal((await call('status')).ai.configured,false);}finally{DB.close();}});


test('uncertain recovery fork preserves checkpoint and debits all prior reserved budget without calling a model',async()=>{const DB=db(),d=fixture(),state=stepRun(newRun(d,{}),d);state.config.mode='ai';state.config.model={provider:'openai',model:'TEST',maxBudget:1,inputPrice:1,outputPrice:1};try{DB.prepare('INSERT INTO datasets VALUES(?,?,?)').bind('d','now',JSON.stringify(d)).run();DB.prepare('INSERT INTO runs VALUES(?,?,0,?,?,?)').bind('parent','d','now','now',JSON.stringify(state)).run();DB.prepare('INSERT INTO model_attempts VALUES(?,?,?,?,?)').bind('parent:0','parent','0.4','uncertain',JSON.stringify({errorCode:'TIMEOUT'})).run();DB.prepare('INSERT INTO model_attempts VALUES(?,?,?,?,?)').bind('parent:old','parent','0.2','done','{}').run();const call=async(body)=>await worker.fetch(new Request('https://local.test/api/runs/parent/fork',{method:'POST',body:JSON.stringify(body)}),{DB});assert.equal((await call({})).status,400);const recovery=await(await worker.fetch(new Request('https://local.test/api/runs/parent/recovery'),{DB})).json();assert.equal(recovery.canFork,true);const response=await call({acknowledgeUncertainRequest:true});assert.equal(response.status,200);const result=await response.json();assert.equal(result.state.index,state.index);assert.deepEqual(result.state.decisions,state.decisions);assert.equal(result.state.forkedFrom.runId,'parent');assert.ok(Math.abs(result.state.config.model.maxBudget-.4)<1e-9);assert.equal(DB.prepare('SELECT status FROM model_attempts WHERE id=?').bind('parent:0').first().status,'uncertain');assert.equal(DB.prepare('SELECT COUNT(*) AS n FROM model_attempts').first().n,2);DB.prepare('UPDATE model_attempts SET status=? WHERE id=?').bind('pending','parent:0').run();assert.equal((await call({acknowledgeUncertainRequest:true})).status,400);}finally{DB.close();}});
