import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import {evidenceDocument,prepareReadingPacket,verifyReadingOutput,summarizeRunReading,READING_REFERENCE_PROTOCOL} from '../worker/reading.js';
import {sha256} from '../worker/collector.js';
import {aiDecision,modelPacket} from '../worker/model.js';
import {newRun,stepRun} from '../worker/engine.js';
import worker from '../dist/server/index.js';

const codes=['600519'];
const source={id:'TEST_REPORT',code:'600519',title:'Synthetic financial report for reading verification',url:'https://example.invalid/report.pdf',kind:'公司公告',availableAt:'2026-09-01T10:00:00+08:00',text:'营业收入为123.45万元，同比增长12.3%。\n本段仅为合成测试资料。',textStatus:'PDF文本已提取'};
const quote='营业收入为123.45万元，同比增长12.3%。';
async function packet(doc=source,limit=2000){const p={asOf:'2026-09-01T15:00:00+08:00',documents:[evidenceDocument(doc,limit)]};const audit=await prepareReadingPacket(p);return {p,audit};}
function output(p,{field='text',excerpt=quote,...overrides}={}){const d=p.documents[0];return {evidenceIds:[d.id],readingReceipt:p.readingChallenge,readingChecks:[{evidenceId:d.id,field,contentHash:field==='text'?d.textHash:d.titleHash,quote:excerpt,claim:'测试资料明确给出了营业收入数值',codes,impact:'neutral',...overrides}]};}
function database(){const sql=new DatabaseSync(':memory:');for(const file of fs.readdirSync('drizzle').filter(x=>x.endsWith('.sql')))sql.exec(fs.readFileSync('drizzle/'+file,'utf8').replaceAll('--> statement-breakpoint',''));const make=(text,args=[])=>({bind(...next){return make(text,next)},first(){return sql.prepare(text).get(...args)||null},all(){return {results:sql.prepare(text).all(...args)}},run(){return {meta:{changes:Number(sql.prepare(text).run(...args).changes)}}}});return {prepare:text=>make(text),batch(statements){sql.exec('BEGIN');try{const result=statements.map(s=>s.run());sql.exec('COMMIT');return result;}catch(error){sql.exec('ROLLBACK');throw error;}},close(){sql.close()}};}
function dataset(){return {start:'2026-09-01',end:'2026-09-02',stocks:[{code:'600519',name:'SYNTHETIC',bars:['2026-08-31','2026-09-01','2026-09-02'].map(date=>({date,open:10,high:10,low:10,close:10,volume:100})),ruleEvidence:[]}],documents:[source],sources:[],coverage:[],warnings:['SYNTHETIC TEST ONLY'],corporateActions:[]};}

test('a verified report excerpt records exact sent text, hashes and numerical facts without claiming understanding',async()=>{const {p,audit}=await packet(),value=output(p,{fact:{label:'营业收入',value:'123.45',unit:'万元'}}),result=verifyReadingOutput(value,audit,codes);assert.equal(result.gatePassed,true);assert.equal(result.status,'text_excerpt_verified');assert.equal(result.counts.verifiedFacts,1);assert.equal(result.checks[0].offset,0);assert.equal(result.documents[0].textHash,await sha256(source.text));assert.equal(result.understandingVerified,false);assert.equal(result.checks[0].semanticClaimVerified,false);assert.equal(result.checks[0].portfolioImpactVerified,false);});
test('a PDF URL with no parsed body can verify its title but cannot be counted as report-body reading',async()=>{const {p,audit}=await packet({...source,text:undefined}),result=verifyReadingOutput(output(p,{field:'title',excerpt:source.title}),audit,codes);assert.equal(result.gatePassed,true);assert.equal(result.status,'title_only_verified');assert.equal(result.counts.verifiedTextExcerpts,0);const invented=verifyReadingOutput(output(p),audit,codes);assert.equal(invented.gatePassed,false);assert.ok(invented.errors.some(e=>e.code==='BODY_NOT_SENT'));});
test('summary text and imported text retain distinct exposure labels',()=>{assert.equal(evidenceDocument({...source,textStatus:'新闻搜索摘要，非全文'}).contentLevel,'summary_excerpt');assert.equal(evidenceDocument({...source,textStatus:undefined}).contentLevel,'provided_text_excerpt');assert.equal(evidenceDocument({...source,text:'正文未解析，只提供标题'}).contentLevel,'metadata_only');});
test('PDF padding is normalized before sending and quotes still match the exact transmitted characters',async()=>{const raw='营业收入              123.45   110.00           12.23\n本表为合成测试资料。',normalized='营业收入 123.45 110.00 12.23';const {p,audit}=await packet({...source,text:raw});assert.equal(p.documents[0].text,normalized+'\n本表为合成测试资料。');assert.equal(p.documents[0].textTruncated,false);assert.equal(p.documents[0].excerptSourceChars,raw.length);assert.equal(p.documents[0].textTransform,'collapse_horizontal_whitespace_v1');assert.equal(verifyReadingOutput(output(p,{excerpt:normalized,fact:{label:'营业收入',value:'123.45',unit:''}}),audit,codes).gatePassed,true);assert.equal(verifyReadingOutput(output(p,{excerpt:'营业收入 999.99 110.00 12.23'}),audit,codes).gatePassed,false);});
test('distinct quotes from one report are verified separately, repeated quotes cannot inflate counts or bypass checks',async()=>{const {p,audit}=await packet(),value=output(p);value.readingChecks.push({...value.readingChecks[0]},{...value.readingChecks[0],quote:'本段仅为合成测试资料。'});const result=verifyReadingOutput(value,audit,codes);assert.equal(result.gatePassed,true);assert.equal(result.counts.verifiedCitations,1);assert.equal(result.counts.verifiedTextExcerpts,2);assert.equal(result.checks[1].redundantQuote,true);value.readingChecks[1].contentHash='FAKE';assert.equal(verifyReadingOutput(value,audit,codes).gatePassed,false);});
test('invented, out-of-packet and truncated-away quotes fail',async()=>{const {p,audit}=await packet();for(const value of [output(p,{excerpt:'营业收入为999.99万元，同比增长99.9%。'}),output(p,{evidenceId:'INVENTED'}),output(p,{contentHash:'0'.repeat(64)})])assert.equal(verifyReadingOutput(value,audit,codes).gatePassed,false);const tail='正文尾部的独特消息不在发送窗口中',partial=await packet({...source,text:'A'.repeat(2000)+tail});assert.equal(partial.p.documents[0].textTruncated,true);assert.equal(partial.p.documents[0].sourceTextChars,2000+tail.length);const result=verifyReadingOutput(output(partial.p,{excerpt:tail}),partial.audit,codes);assert.ok(result.errors.some(e=>e.code==='QUOTE_NOT_IN_SENT_CONTENT'));});
test('a stale receipt cannot validate a new request, and citing only titles does not verify available text',async()=>{const a=await packet(),b=await packet();const stale=verifyReadingOutput(output(a.p),b.audit,codes);assert.ok(stale.errors.some(e=>e.code==='RECEIPT_MISMATCH'));const titles=verifyReadingOutput(output(a.p,{field:'title',excerpt:source.title}),a.audit,codes);assert.ok(titles.errors.some(e=>e.code==='AVAILABLE_TEXT_NOT_VERIFIED'));});
test('incorrect financial values, unknown stocks and uncovered citations fail',async()=>{const {p,audit}=await packet();const wrong=verifyReadingOutput(output(p,{fact:{label:'营业收入',value:'999.99',unit:'万元'}}),audit,codes);assert.ok(wrong.errors.some(e=>e.code==='FACT_NOT_IN_QUOTE'));assert.equal(verifyReadingOutput(output(p,{codes:['000001']}),audit,codes).gatePassed,false);const noQuote=verifyReadingOutput({evidenceIds:[source.id],readingReceipt:p.readingChallenge,readingChecks:[]},audit,codes);assert.ok(noQuote.errors.some(e=>e.code==='CITATION_WITHOUT_VERIFIED_QUOTE'));});
test('future documents fail independently and an empty as-of packet is explicitly not a reading proof',async()=>{const future=await packet({...source,availableAt:'2026-09-02T10:00:00+08:00'});assert.ok(verifyReadingOutput(output(future.p),future.audit,codes).errors.some(e=>e.code==='FUTURE_OR_UNDATED_DOCUMENT_SENT'));const p={asOf:'2026-09-01T15:00:00+08:00',documents:[]},audit=await prepareReadingPacket(p),result=verifyReadingOutput({evidenceIds:[]},audit,codes);assert.equal(result.status,'no_visible_documents');assert.equal(result.gatePassed,true);assert.equal(result.counts.verifiedTextExcerpts,0);});
test('old evidence IDs do not retroactively become verified-reading records',()=>{const state={config:{mode:'ai'},decisions:[{date:'2026-09-01',evidenceIds:[source.id],retrieval:{returnedDocuments:1}}]};const summary=summarizeRunReading(state);assert.equal(summary.totalDecisions,1);assert.equal(summary.legacyUnverified,1);assert.equal(summary.verifiedTextDecisions,0);assert.equal(summary.understandingVerified,false);});
test('an empty news corpus rejects stock codes masquerading as document reading receipts',async()=>{const p={asOf:'2026-09-01T15:00:00+08:00',documents:[]},audit=await prepareReadingPacket(p);assert.equal(p.readingInstructions.noDocuments,true);assert.deepEqual(p.readingInstructions.allowedEvidenceIds,[]);const result=verifyReadingOutput({evidenceIds:[],readingChecks:[{evidenceId:'600519',field:'title',quote:'合成股票行情不是新闻文档',claim:'合成伪造阅读',codes,impact:'neutral'}]},audit,codes);assert.equal(result.gatePassed,false);assert.ok(result.errors.some(error=>error.code==='DOCUMENT_NOT_SENT'));assert.equal(result.checks[0].quote,'合成股票行情不是新闻文档');assert.equal(result.counts.verifiedNewsDocuments,0);});
test('daily news reading cannot be satisfied by a report-only quote when news is available',async()=>{const news={...source,id:'TEST_NEWS',kind:'财经报刊新闻元数据',title:'合成测试公司发布业绩相关新闻',text:undefined};const p={asOf:'2026-09-01T15:00:00+08:00',documents:[evidenceDocument(source),evidenceDocument(news)],readingRequirements:{requireNewsQuote:true}},audit=await prepareReadingPacket(p),value=output(p);let result=verifyReadingOutput(value,audit,codes);assert.equal(result.gatePassed,false);assert.ok(result.errors.some(e=>e.code==='AVAILABLE_NEWS_NOT_VERIFIED'));value.evidenceIds.push(news.id);value.readingChecks.push({evidenceId:news.id,field:'title',contentHash:p.documents[1].titleHash,quote:news.title,claim:'合成测试新闻标题',codes,impact:'neutral'});result=verifyReadingOutput(value,audit,codes);assert.equal(result.gatePassed,true);assert.equal(result.counts.verifiedNewsDocuments,1);assert.equal(result.counts.verifiedNewsTextExcerpts,0);});
test('repeating an old news quote cannot satisfy a day with newly available news',async()=>{const old={...source,id:'OLD_NEWS',kind:'财经报刊新闻元数据',title:'合成测试旧新闻标题供回看',text:undefined,availableAt:'2026-08-31T10:00:00+08:00'},fresh={...old,id:'NEW_NEWS',title:'合成测试新新闻标题供当天阅读',availableAt:'2026-09-01T10:00:00+08:00'};const p={asOf:'2026-09-01T15:00:00+08:00',documents:[evidenceDocument(old),evidenceDocument(fresh)],readingRequirements:{requireNewsQuote:true,requireNewNewsQuote:true,previousCutoff:'2026-08-31T15:00:00+08:00'}},audit=await prepareReadingPacket(p),value=output(p,{field:'title',excerpt:old.title});let result=verifyReadingOutput(value,audit,codes);assert.equal(result.gatePassed,false);assert.ok(result.errors.some(e=>e.code==='AVAILABLE_NEW_NEWS_NOT_VERIFIED'));value.evidenceIds=[fresh.id];value.readingChecks=[{...value.readingChecks[0],evidenceId:fresh.id,contentHash:p.documents[1].titleHash,quote:fresh.title}];result=verifyReadingOutput(value,audit,codes);assert.equal(result.gatePassed,true);assert.equal(result.counts.verifiedNewNewsDocuments,1);});
test('daily model retrieval prioritizes current news and excludes future news while preserving report checks',async()=>{const DB=database(),d=dataset(),news={...source,id:'CURRENT_NEWS',kind:'财经报刊新闻元数据',title:'合成测试公司当日业绩相关新闻',text:undefined};d.documents.push(news,{...news,id:'FUTURE_NEWS',availableAt:'2026-09-02T10:00:00+08:00'});const state=newRun(d,{requireNewsReading:true,retrievalMode:'ai_search',ruleMode:'research_assumptions',acknowledgeUnverifiedRules:true});let calls=0;const fetcher=async(url,options)=>{calls++;const p=JSON.parse(JSON.parse(options.body).messages[1].content);if(calls===1)return Response.json({choices:[{finish_reason:'stop',message:{content:JSON.stringify({queries:[{query:'季度报告',codes}]})}}]});assert.equal(p.documents[0].id,news.id);assert.ok(!p.documents.some(x=>x.id==='FUTURE_NEWS'));assert.deepEqual(p.readingRequirements.newNewsDocumentIds,[news.id]);const n=p.documents.find(x=>x.id===news.id),report=p.documents.find(x=>x.id===source.id);return Response.json({choices:[{finish_reason:'stop',message:{content:JSON.stringify({weights:{'600519':.8},reason:'SYNTHETIC daily reading',evidenceIds:[news.id,source.id],readingReceipt:p.readingChallenge,readingChecks:[{evidenceId:news.id,field:'title',contentHash:n.titleHash,quote:news.title,claim:'合成测试新闻',codes,impact:'neutral'},{evidenceId:source.id,field:'text',contentHash:report.textHash,quote,claim:'合成测试财报',codes,impact:'neutral'}]})}}]});};try{const result=await aiDecision({SILICONFLOW_API_KEY:'TEST_ONLY_KEY'},DB,'news-first',0,state,d,'2026-09-01',{provider:'siliconflow',model:'Qwen/Qwen3-8B',maxBudget:0},fetcher);assert.equal(result.readingAudit.gatePassed,true);assert.equal(result.readingAudit.counts.verifiedNewsDocuments,1);assert.equal(result.requests,2);}finally{DB.close();}});
test('compact prices preserve every past OHLC value and omit future rows, while timeouts remain bounded',()=>{const d=dataset(),normal=newRun(d,{}),compact=newRun(d,{compactPrices:true,modelTimeoutSeconds:180}),a=modelPacket(normal,d,'2026-09-01'),b=modelPacket(compact,d,'2026-09-01');assert.deepEqual(b.priceColumns,['date','open','high','low','close']);assert.deepEqual(b.prices[0].bars.map(row=>Object.fromEntries(b.priceColumns.map((column,index)=>[column,row[index]]))),a.prices[0].bars);assert.ok(b.prices[0].bars.every(row=>row[0]<='2026-09-01'));assert.equal(compact.config.modelTimeoutSeconds,180);assert.throws(()=>newRun(d,{modelTimeoutSeconds:181}));});
test('explicit final-close reading calls AI and records proof without a pending out-of-window order',async()=>{const DB=database(),d=dataset();let state=stepRun(newRun(d,{frequency:1,readAtFinalClose:true,ruleMode:'research_assumptions',acknowledgeUnverifiedRules:true}),d);state.config.mode='ai';state.config.model={provider:'siliconflow',model:'Qwen/Qwen3-8B',maxBudget:0};DB.prepare('INSERT INTO datasets VALUES(?,?,?)').bind('d','now',JSON.stringify(d)).run();DB.prepare('INSERT INTO runs VALUES(?,?,0,?,?,?)').bind('final','d','now','now',JSON.stringify(state)).run();const original=globalThis.fetch;let calls=0;globalThis.fetch=async(url,options)=>{calls++;const p=JSON.parse(JSON.parse(options.body).messages[1].content);return Response.json({choices:[{finish_reason:'stop',message:{content:JSON.stringify({...output(p),weights:{'600519':.8},reason:'SYNTHETIC final-close reading only'})}}]});};try{const response=await worker.fetch(new Request('https://local.test/api/runs/final/step',{method:'POST',body:JSON.stringify({expectedVersion:0})}),{DB,SILICONFLOW_API_KEY:'TEST_ONLY_KEY'}),result=await response.json();assert.equal(response.status,200,JSON.stringify(result));assert.equal(calls,1);assert.equal(result.state.status,'completed');assert.equal(result.state.pending,null);assert.equal(result.state.decisions.at(-1).date,d.end);assert.equal(result.state.decisions.at(-1).executionEligible,false);assert.equal(result.state.decisions.at(-1).readingAudit.gatePassed,true);assert.ok(result.state.trades.every(t=>t.date<=d.end));}finally{globalThis.fetch=original;DB.close();}});
test('model call stores the actual request hash, verified excerpt and immutable idempotent result',async()=>{const DB=database(),d=dataset(),state=newRun(d,{ruleMode:'research_assumptions',acknowledgeUnverifiedRules:true});let calls=0,body;try{const fetcher=async(url,options)=>{calls++;body=options.body;const p=JSON.parse(JSON.parse(body).messages[1].content);return Response.json({id:'TEST_PROVIDER_RESPONSE',model:'TEST_MODEL',choices:[{finish_reason:'stop',message:{content:JSON.stringify({...output(p),allocationScores:{'600519':100},investedFraction:.8,reason:'SYNTHETIC verified decision'})}}],usage:{prompt_tokens:10,completion_tokens:20,total_tokens:30}});};const env={SILICONFLOW_API_KEY:'TEST_ONLY_KEY'},config={provider:'siliconflow',model:'Qwen/Qwen3-8B',maxBudget:0};const result=await aiDecision(env,DB,'verified',0,state,d,'2026-09-01',config,fetcher);assert.equal(result.readingAudit.requestHash,await sha256(body));assert.equal(result.readingAudit.delivery,'provider_response_received');assert.equal(result.readingAudit.providerRequestId,'TEST_PROVIDER_RESPONSE');assert.equal(result.readingAudit.status,'text_excerpt_verified');assert.equal(result.readingAudit.mode,'enforce');const saved=JSON.parse(DB.prepare('SELECT payload FROM model_attempts WHERE id=?').bind('verified:0').first().payload);assert.equal(saved.readingAudit.documents[0].text,source.text);assert.ok(!JSON.stringify(saved).includes('TEST_ONLY_KEY'));assert.deepEqual(await aiDecision(env,DB,'verified',0,state,d,'2026-09-01',config,fetcher),result);assert.equal(calls,1);}finally{DB.close();}});
test('API rejects a fabricated reading proof before persisting a decision or placing a pending trade',async()=>{const DB=database(),d=dataset(),state=newRun(d,{ruleMode:'research_assumptions',acknowledgeUnverifiedRules:true});state.config.mode='ai';state.config.model={provider:'siliconflow',model:'Qwen/Qwen3-8B',maxBudget:0};DB.prepare('INSERT INTO datasets VALUES(?,?,?)').bind('d','now',JSON.stringify(d)).run();DB.prepare('INSERT INTO runs VALUES(?,?,0,?,?,?)').bind('r','d','now','now',JSON.stringify(state)).run();const original=globalThis.fetch;let calls=0;globalThis.fetch=async(url,options)=>{calls++;const p=JSON.parse(JSON.parse(options.body).messages[1].content);return Response.json({choices:[{finish_reason:'stop',message:{content:JSON.stringify({...output(p,{excerpt:'营业收入为999.99万元，同比增长99.9%。'}),weights:{'600519':1},reason:'SYNTHETIC fabricated proof'})}}]});};try{const response=await worker.fetch(new Request('https://local.test/api/runs/r/step',{method:'POST',body:JSON.stringify({expectedVersion:0})}),{DB,SILICONFLOW_API_KEY:'TEST_ONLY_KEY'});assert.equal(response.status,400);assert.match((await response.json()).error,/READING_VERIFICATION_FAILED/);const row=DB.prepare('SELECT version,payload FROM runs WHERE id=?').bind('r').first(),saved=JSON.parse(row.payload);assert.equal(row.version,0);assert.equal(saved.decisions.length,0);assert.equal(saved.pending,null);const attempt=DB.prepare('SELECT status,payload FROM model_attempts WHERE id=?').bind('r:0').first();assert.equal(attempt.status,'uncertain');assert.ok(JSON.parse(attempt.payload).readingAudit.errors.some(e=>e.code==='QUOTE_NOT_IN_SENT_CONTENT'));const read=await(await worker.fetch(new Request('https://local.test/api/runs/r/reading-audit'),{DB})).json();assert.equal(read.currentAttempt.readingAudit.status,'failed');assert.equal(calls,1);}finally{globalThis.fetch=original;DB.close();}});

async function referencePacket(doc=source){const p={asOf:'2026-09-01T15:00:00+08:00',documents:[evidenceDocument(doc)]};const audit=await prepareReadingPacket(p,{protocol:READING_REFERENCE_PROTOCOL});return {p,audit};}
function referenceOutput(p,overrides={}){return {readingReceipt:p.readingChallenge,readingChecks:[{reference:p.documents[0].textReference,quote,claim:'合成测试营业收入资料',codes,impact:'neutral',...overrides}]};}
test('short references bind exact quotes to server-side hashes and preserve canonical source IDs',async()=>{const {p,audit}=await referencePacket(),result=verifyReadingOutput(referenceOutput(p),audit,codes);assert.equal(p.documents[0].titleReference,'D01T');assert.equal(p.documents[0].textReference,'D01B');assert.equal(result.gatePassed,true);assert.deepEqual(result.citedEvidenceIds,[source.id]);assert.equal(result.checks[0].contentHash,await sha256(source.text));assert.equal(result.checks[0].receivedContentHash,null);assert.equal(result.checks[0].hashEchoRequired,false);assert.equal(result.checks[0].offset,0);assert.equal(result.understandingVerified,false);});
test('unknown references and contradictory IDs, fields, hashes or citations cannot silently be repaired',async()=>{const {p,audit}=await referencePacket();for(const [overrides,error] of [[{reference:'D99B'},'REFERENCE_NOT_SENT'],[{evidenceId:'OTHER'},'REFERENCE_ID_CONFLICT'],[{field:'title'},'REFERENCE_FIELD_CONFLICT'],[{contentHash:'BAD'},'CONTENT_HASH_MISMATCH']]){const result=verifyReadingOutput(referenceOutput(p,overrides),audit,codes);assert.equal(result.gatePassed,false);assert.ok(result.errors.some(x=>x.code===error));}const value={...referenceOutput(p),evidenceIds:['OTHER']};assert.ok(verifyReadingOutput(value,audit,codes).errors.some(x=>x.code==='CITATION_REFERENCE_CONFLICT'));});
test('reference protocol still rejects stale receipts, false quotes, future sources and nonexistent bodies',async()=>{const a=await referencePacket(),b=await referencePacket();assert.ok(verifyReadingOutput(referenceOutput(a.p),b.audit,codes).errors.some(x=>x.code==='RECEIPT_MISMATCH'));assert.ok(verifyReadingOutput(referenceOutput(a.p,{quote:'营业收入为999.99万元，同比增长99.9%。'}),a.audit,codes).errors.some(x=>x.code==='QUOTE_NOT_IN_SENT_CONTENT'));const future=await referencePacket({...source,availableAt:'2026-09-02T10:00:00+08:00'});assert.equal(verifyReadingOutput(referenceOutput(future.p),future.audit,codes).gatePassed,false);const title=await referencePacket({...source,text:undefined});assert.equal(title.p.documents[0].textReference,null);assert.equal(verifyReadingOutput(referenceOutput(title.p,{reference:'D01B'}),title.audit,codes).gatePassed,false);});
test('references cannot attribute a different document quote or substitute old news for newly available news',async()=>{const old={...source,id:'OLD_NEWS',kind:'财经报刊新闻元数据',title:'合成测试旧新闻标题供回看',text:undefined,availableAt:'2026-08-31T10:00:00+08:00'},fresh={...old,id:'NEW_NEWS',title:'合成测试新新闻标题供当天阅读',availableAt:'2026-09-01T10:00:00+08:00'};const p={asOf:'2026-09-01T15:00:00+08:00',documents:[evidenceDocument(old),evidenceDocument(fresh)],readingRequirements:{requireNewsQuote:true,requireNewNewsQuote:true,previousCutoff:'2026-08-31T15:00:00+08:00'}},audit=await prepareReadingPacket(p,{protocol:READING_REFERENCE_PROTOCOL});let value=referenceOutput(p,{reference:'D01T',quote:old.title}),result=verifyReadingOutput(value,audit,codes);assert.ok(result.errors.some(x=>x.code==='AVAILABLE_NEW_NEWS_NOT_VERIFIED'));value=referenceOutput(p,{reference:'D01T',quote:fresh.title});assert.ok(verifyReadingOutput(value,audit,codes).errors.some(x=>x.code==='QUOTE_NOT_IN_SENT_CONTENT'));value=referenceOutput(p,{reference:'D02T',quote:fresh.title});assert.equal(verifyReadingOutput(value,audit,codes).gatePassed,true);});
test('reference model decisions persist source IDs with idempotent exact request audit and no credential material',async()=>{const DB=database(),d=dataset(),state=newRun(d,{readingProtocol:READING_REFERENCE_PROTOCOL,ruleMode:'research_assumptions',acknowledgeUnverifiedRules:true});let calls=0,body;try{const fetcher=async(url,options)=>{calls++;body=options.body;const p=JSON.parse(JSON.parse(body).messages[1].content);return Response.json({choices:[{finish_reason:'stop',message:{content:JSON.stringify({...referenceOutput(p),allocationScores:{'600519':100},investedFraction:.8,reason:'SYNTHETIC reference quote decision'})}}]});};const env={SILICONFLOW_API_KEY:'TEST_ONLY_KEY'},config={provider:'siliconflow',model:'Qwen/Qwen3-8B',maxBudget:0};const result=await aiDecision(env,DB,'references',0,state,d,'2026-09-01',config,fetcher);assert.equal(result.readingAudit.gatePassed,true);assert.equal(result.readingAudit.requestHash,await sha256(body));assert.deepEqual(result.decision.evidenceIds,[source.id]);assert.equal(result.readingAudit.checks[0].hashEchoRequired,false);const saved=DB.prepare('SELECT payload FROM model_attempts WHERE id=?').bind('references:0').first();assert.ok(!saved.payload.includes('TEST_ONLY_KEY'));assert.deepEqual(await aiDecision(env,DB,'references',0,state,d,'2026-09-01',config,fetcher),result);assert.equal(calls,1);}finally{DB.close();}});
test('reading summaries preserve mixed historical protocols without relabeling earlier proofs',()=>{const summary=summarizeRunReading({config:{mode:'ai'},decisions:[{date:'2026-09-01',readingAudit:{protocol:'excerpt_receipt_v1',status:'title_only_verified',gatePassed:true}},{date:'2026-09-02',readingAudit:{protocol:READING_REFERENCE_PROTOCOL,status:'title_only_verified',gatePassed:true}}]});assert.equal(summary.protocol,'mixed');assert.deepEqual(summary.protocols,['excerpt_receipt_v1',READING_REFERENCE_PROTOCOL]);assert.equal(summary.decisions[0].protocol,'excerpt_receipt_v1');});
test('focused daily packets cover company news and a visible parsed report without flooding duplicate metadata',async()=>{const DB=database(),d=dataset(),pool=Array.from({length:12},(_,i)=>String(600519+i));d.stocks=pool.map(code=>({...d.stocks[0],code}));d.documents=[source,...pool.flatMap(code=>Array.from({length:4},(_,i)=>({...source,id:'NEWS_'+code+'_'+i,code,kind:'财经报刊新闻元数据',text:undefined,title:'合成测试当日公司新闻_'+code+'_'+i})))];d.documents.push({...source,id:'FUTURE_PARSED_REPORT',availableAt:'2026-09-02T10:00:00+08:00'});const state=newRun(d,{requireNewsReading:true,readingProtocol:READING_REFERENCE_PROTOCOL,retrievalMode:'ai_search',ruleMode:'research_assumptions',acknowledgeUnverifiedRules:true});let calls=0;try{const fetcher=async(url,options)=>{calls++;const p=JSON.parse(JSON.parse(options.body).messages[1].content);if(calls===1)return Response.json({choices:[{finish_reason:'stop',message:{content:JSON.stringify({queries:[{query:'合成测试新闻',codes:pool}]})}}]});assert.ok(p.documents.length<=14);assert.ok(pool.every(code=>p.documents.some(doc=>/新闻/.test(doc.kind)&&doc.code===code)));assert.ok(p.documents.every(doc=>doc.availableAt<=p.asOf));const news=p.documents.find(doc=>doc.titleReference===p.readingRequirements.requiredReferences[0]),body=p.documents.find(doc=>doc.textReference);assert.ok(body);assert.equal(body.text,source.text);assert.ok(!('id' in news));assert.ok(!('titleHash' in news));return Response.json({choices:[{finish_reason:'stop',message:{content:JSON.stringify({allocationScores:Object.fromEntries(pool.map(code=>[code,10])),investedFraction:.8,reason:'SYNTHETIC focused daily data',readingReceipt:p.readingChallenge,readingChecks:[{reference:news.titleReference,quote:news.title,claim:'合成测试当日新闻',codes:[news.code],impact:'neutral'},{reference:body.textReference,quote,claim:'合成测试财报文本',codes,impact:'neutral'}]})}}]});};const result=await aiDecision({SILICONFLOW_API_KEY:'TEST_ONLY_KEY'},DB,'focused',0,state,d,'2026-09-01',{provider:'siliconflow',model:'Qwen/Qwen3-8B',maxBudget:0},fetcher);assert.equal(result.readingAudit.gatePassed,true);assert.equal(result.readingAudit.counts.verifiedNewNewsDocuments,1);assert.equal(result.readingAudit.counts.verifiedTextExcerpts,1);assert.ok(result.readingAudit.documents.every(doc=>!doc.id.includes('FUTURE')));assert.ok(result.retrieval.queries.some(q=>q.plannedBy==='platform_parsed_text_guard'));}finally{DB.close();}});
test('search-query hits do not become company news unless the title mentions the company or the source provides its code',async()=>{const {relatedStockCodes,documentForStock}=await import('../worker/reading.js'),d=dataset();d.stocks[0].name='兴业银行';const hit={...source,id:'UNRELATED_NEWS',code:null,title:'宏工科技：股东减持股份公告',kind:'财经报刊新闻元数据',text:undefined,association:{basis:'search_query_not_verified_ticker',requestedCompanyCode:'600519'}};assert.deepEqual(relatedStockCodes(hit,d.stocks),[]);assert.equal(documentForStock(hit,d.stocks[0]),false);d.documents=[hit];const {searchEvidence,auditDataset}=await import('../worker/quality.js');assert.equal(searchEvidence(d,d.start).returnedDocuments,0);const row=auditDataset(d).stocks[0];assert.equal(row.news,0);assert.equal(row.newsSearchHits,1);assert.equal(row.unverifiedNewsHits,1);hit.title='兴业银行：公司经营研究公告';assert.deepEqual(relatedStockCodes(hit,d.stocks),codes);assert.equal(searchEvidence(d,d.start).returnedDocuments,1);});
test('financial windows find numerical rows beyond a long report cover and a table header alone cannot satisfy numerical reading',async()=>{const report={...source,text:'SYNTHETIC COVER ONLY\n'.repeat(200)+'营业收入       123.45       110.00\n净利润 20.00 18.00\n',title:'合成公司2026年半年度报告'},doc=evidenceDocument(report),p={asOf:'2026-09-01T15:00:00+08:00',documents:[doc],readingRequirements:{requireFinancialFact:true}},audit=await prepareReadingPacket(p,{protocol:READING_REFERENCE_PROTOCOL});assert.ok(doc.excerptSourceOffset>2000);assert.equal(doc.financialFactExpected.value,'123.45');assert.ok(!p.documents[0].financialFactExpected);assert.equal(p.documents[0].financialFactQuestion,'营业收入');const header=referenceOutput(p,{quote:'SYNTHETIC COVER ONLY'});assert.ok(verifyReadingOutput(header,audit,codes).errors.some(e=>e.code==='AVAILABLE_FINANCIAL_FACT_NOT_VERIFIED'));const valid=referenceOutput(p,{quote:'营业收入 123.45 110.00',fact:{label:'营业收入',value:'123.45',unit:''}});let result=verifyReadingOutput(valid,audit,codes);assert.equal(result.gatePassed,true);assert.equal(result.counts.verifiedFinancialFacts,1);valid.readingChecks[0].fact.value='110.00';result=verifyReadingOutput(valid,audit,codes);assert.equal(result.gatePassed,false);assert.ok(result.errors.some(e=>e.code==='FINANCIAL_VALUE_MISMATCH'));});
test('a correctly copied news title cannot be attributed to an unsupported portfolio stock',async()=>{const doc=evidenceDocument({...source,kind:'财经新闻',text:undefined,relatedStockCodes:['600519']}),p={asOf:'2026-09-01T15:00:00+08:00',documents:[doc]},audit=await prepareReadingPacket(p,{protocol:READING_REFERENCE_PROTOCOL}),value=referenceOutput(p,{reference:'D01T',quote:source.title,codes:['600036']});const result=verifyReadingOutput(value,audit,['600519','600036']);assert.ok(result.errors.some(e=>e.code==='STOCK_NOT_SUPPORTED_BY_DOCUMENT'));assert.equal(result.gatePassed,false);});
test('small raw-price windows retain point-in-time 30-record statistics and never include a future price',async()=>{const {priceFeatures}=await import('../worker/model.js'),d=dataset();d.stocks[0].bars=Array.from({length:35},(_,i)=>({date:new Date(Date.UTC(2026,7,1+i)).toISOString().slice(0,10),open:100+i,high:101+i,low:99+i,close:100+i,volume:100}));d.stocks[0].bars.push({date:'2026-09-10',open:99999,high:99999,low:99999,close:99999,volume:100});const state=newRun(d,{priceWindowDays:5}),p=modelPacket(state,d,'2026-09-01'),features=priceFeatures(d.stocks[0],'2026-09-01');assert.equal(p.prices[0].bars.length,5);assert.equal(features.records,30);assert.equal(features.lastClose,131);assert.equal(features.lastDate,'2026-09-01');assert.equal(features.return5,131/126-1);assert.equal(features.meanClose20,121.5);assert.equal(features.maxCloseDrawdown20,0);assert.equal(p.priceFeatures[0].lastClose,131);assert.ok(p.prices[0].bars.every(b=>b.close<99999));assert.throws(()=>newRun(d,{priceWindowDays:4}));});
test('a copied financial row verifies its literal number without inventing a missing model fact field or a unit',async()=>{const report={...source,text:'营业收入 123.45 110.00\n合成测试财务数据。'},p={asOf:'2026-09-01T15:00:00+08:00',documents:[evidenceDocument(report)],readingRequirements:{requireFinancialFact:true}},audit=await prepareReadingPacket(p,{protocol:READING_REFERENCE_PROTOCOL}),value=referenceOutput(p,{quote:'营业收入 123.45 110.00'}),result=verifyReadingOutput(value,audit,codes);assert.equal(result.gatePassed,true);assert.equal(result.counts.verifiedFinancialFacts,1);assert.equal(result.checks[0].fact,undefined);assert.equal(result.returnedReading.readingChecks[0].fact,undefined);assert.equal(result.checks[0].verifiedFinancialFact.method,'server_extract_from_verified_quote');assert.equal(result.checks[0].verifiedFinancialFact.unit,null);assert.equal(result.checks[0].verifiedFinancialFact.periodVerified,false);value.readingChecks[0].fact={label:'营业收入',value:'110.00',unit:''};assert.equal(verifyReadingOutput(value,audit,codes).gatePassed,false);});
test('invalid allocation, malformed JSON and truncated output retain raw API responses and known usage without retry',async()=>{
 for(const [rawOutput,finishReason,errorCode] of [['{"allocationScores":{"600519":10}}','stop','模型配置分数不合法'],['{ malformed synthetic output','stop','INVALID_JSON'],['{"unfinished":','length','INCOMPLETE_OUTPUT']]){
  const DB=database(),d=dataset(),state=newRun(d,{ruleMode:'research_assumptions',acknowledgeUnverifiedRules:true});let calls=0;
  try{
   const fetcher=async()=>{calls++;return Response.json({id:'SYNTHETIC_RESPONSE',choices:[{finish_reason:finishReason,message:{content:rawOutput}}],usage:{prompt_tokens:10,completion_tokens:3,total_tokens:13}});};
   await assert.rejects(aiDecision({SILICONFLOW_API_KEY:'TEST_ONLY_KEY'},DB,'raw-failure',0,state,d,d.start,{provider:'siliconflow',model:'Qwen/Qwen3-8B',maxBudget:0},fetcher));
   const saved=JSON.parse(DB.prepare('SELECT payload FROM model_attempts WHERE id=?').bind('raw-failure:0').first().payload);
   assert.equal(saved.errorCode,errorCode);assert.equal(saved.completedRequests,1);assert.equal(saved.usage[0].total_tokens,13);assert.equal(saved.responseOutputs[0].rawOutput,rawOutput);assert.equal(saved.responseOutputs[0].finishReason,finishReason);assert.ok(!JSON.stringify(saved).includes('TEST_ONLY_KEY'));
   await assert.rejects(aiDecision({SILICONFLOW_API_KEY:'TEST_ONLY_KEY'},DB,'raw-failure',0,state,d,d.start,{provider:'siliconflow',model:'Qwen/Qwen3-8B',maxBudget:0},fetcher));assert.equal(calls,1);assert.equal(state.decisions.length,0);assert.equal(state.pending,null);
  }finally{DB.close();}
 }
});
test('a table heading followed by years on another line is not a financial amount',async()=>{
 const {financialFactChallenge}=await import('../worker/reading.js');
 assert.equal(financialFactChallenge('营业收入\n2026年 2025年\n合成测试表头'),null);
 assert.deepEqual(financialFactChallenge('营业收入 123.45 110.00'),{label:'营业收入',value:'123.45',offset:0});
});
