import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import {evidenceDocument,prepareReadingPacket,verifyReadingOutput,summarizeRunReading} from '../worker/reading.js';
import {sha256} from '../worker/collector.js';
import {aiDecision} from '../worker/model.js';
import {newRun} from '../worker/engine.js';
import worker from '../dist/server/index.js';

const codes=['600519'];
const source={id:'TEST_REPORT',code:'600519',title:'Synthetic financial report for reading verification',url:'https://example.invalid/report.pdf',kind:'公司公告',availableAt:'2026-09-01T10:00:00+08:00',text:'营业收入为123.45万元，同比增长12.3%。\n本段仅为合成测试资料。',textStatus:'PDF文本已提取'};
const quote='营业收入为123.45万元，同比增长12.3%。';
async function packet(doc=source,limit=2000){const p={asOf:'2026-09-01T15:00:00+08:00',documents:[evidenceDocument(doc,limit)]};const audit=await prepareReadingPacket(p);return {p,audit};}
function output(p,{field='text',excerpt=quote,...overrides}={}){const d=p.documents[0];return {evidenceIds:[d.id],readingReceipt:p.readingChallenge,readingChecks:[{evidenceId:d.id,field,contentHash:field==='text'?d.textHash:d.titleHash,quote:excerpt,claim:'测试资料明确给出了营业收入数值',codes,impact:'neutral',...overrides}]};}
function database(){const sql=new DatabaseSync(':memory:');for(const file of fs.readdirSync('drizzle').filter(x=>x.endsWith('.sql')))sql.exec(fs.readFileSync('drizzle/'+file,'utf8').replaceAll('--> statement-breakpoint',''));const make=(text,args=[])=>({bind(...next){return make(text,next)},first(){return sql.prepare(text).get(...args)||null},all(){return {results:sql.prepare(text).all(...args)}},run(){return {meta:{changes:Number(sql.prepare(text).run(...args).changes)}}}});return {prepare:text=>make(text),batch(statements){sql.exec('BEGIN');try{const result=statements.map(s=>s.run());sql.exec('COMMIT');return result;}catch(error){sql.exec('ROLLBACK');throw error;}},close(){sql.close()}};}
function dataset(){return {start:'2026-09-01',end:'2026-09-02',stocks:[{code:'600519',name:'SYNTHETIC',bars:['2026-08-31','2026-09-01','2026-09-02'].map(date=>({date,open:10,high:10,low:10,close:10,volume:100})),ruleEvidence:[]}],documents:[source],sources:[],coverage:[],warnings:['SYNTHETIC TEST ONLY'],corporateActions:[]};}

test('a verified report excerpt records exact sent text, hashes and numerical facts without claiming understanding',async()=>{const {p,audit}=await packet(),value=output(p,{fact:{label:'营业收入',value:'123.45',unit:'万元'}}),result=verifyReadingOutput(value,audit,codes);assert.equal(result.gatePassed,true);assert.equal(result.status,'text_excerpt_verified');assert.equal(result.counts.verifiedFacts,1);assert.equal(result.checks[0].offset,0);assert.equal(result.documents[0].textHash,await sha256(source.text));assert.equal(result.understandingVerified,false);assert.equal(result.checks[0].semanticClaimVerified,false);assert.equal(result.checks[0].portfolioImpactVerified,false);});
test('a PDF URL with no parsed body can verify its title but cannot be counted as report-body reading',async()=>{const {p,audit}=await packet({...source,text:undefined}),result=verifyReadingOutput(output(p,{field:'title',excerpt:source.title}),audit,codes);assert.equal(result.gatePassed,true);assert.equal(result.status,'title_only_verified');assert.equal(result.counts.verifiedTextExcerpts,0);const invented=verifyReadingOutput(output(p),audit,codes);assert.equal(invented.gatePassed,false);assert.ok(invented.errors.some(e=>e.code==='BODY_NOT_SENT'));});
test('summary text and imported text retain distinct exposure labels',()=>{assert.equal(evidenceDocument({...source,textStatus:'新闻搜索摘要，非全文'}).contentLevel,'summary_excerpt');assert.equal(evidenceDocument({...source,textStatus:undefined}).contentLevel,'provided_text_excerpt');assert.equal(evidenceDocument({...source,text:'正文未解析，只提供标题'}).contentLevel,'metadata_only');});
test('PDF padding is normalized before sending and quotes still match the exact transmitted characters',async()=>{const raw='营业收入              123.45   110.00           12.23\n本表为合成测试资料。',normalized='营业收入 123.45 110.00 12.23';const {p,audit}=await packet({...source,text:raw});assert.equal(p.documents[0].text,normalized+'\n本表为合成测试资料。');assert.equal(p.documents[0].textTruncated,false);assert.equal(p.documents[0].excerptSourceChars,raw.length);assert.equal(p.documents[0].textTransform,'collapse_horizontal_whitespace_v1');assert.equal(verifyReadingOutput(output(p,{excerpt:normalized,fact:{label:'营业收入',value:'123.45',unit:''}}),audit,codes).gatePassed,true);assert.equal(verifyReadingOutput(output(p,{excerpt:'营业收入 999.99 110.00 12.23'}),audit,codes).gatePassed,false);});
test('distinct quotes from one report are verified separately, repeated quotes cannot inflate counts or bypass checks',async()=>{const {p,audit}=await packet(),value=output(p);value.readingChecks.push({...value.readingChecks[0]},{...value.readingChecks[0],quote:'本段仅为合成测试资料。'});const result=verifyReadingOutput(value,audit,codes);assert.equal(result.gatePassed,true);assert.equal(result.counts.verifiedCitations,1);assert.equal(result.counts.verifiedTextExcerpts,2);assert.equal(result.checks[1].redundantQuote,true);value.readingChecks[1].contentHash='FAKE';assert.equal(verifyReadingOutput(value,audit,codes).gatePassed,false);});
test('invented, out-of-packet and truncated-away quotes fail',async()=>{const {p,audit}=await packet();for(const value of [output(p,{excerpt:'营业收入为999.99万元，同比增长99.9%。'}),output(p,{evidenceId:'INVENTED'}),output(p,{contentHash:'0'.repeat(64)})])assert.equal(verifyReadingOutput(value,audit,codes).gatePassed,false);const tail='正文尾部的独特消息不在发送窗口中',partial=await packet({...source,text:'A'.repeat(2000)+tail});assert.equal(partial.p.documents[0].textTruncated,true);assert.equal(partial.p.documents[0].sourceTextChars,2000+tail.length);const result=verifyReadingOutput(output(partial.p,{excerpt:tail}),partial.audit,codes);assert.ok(result.errors.some(e=>e.code==='QUOTE_NOT_IN_SENT_CONTENT'));});
test('a stale receipt cannot validate a new request, and citing only titles does not verify available text',async()=>{const a=await packet(),b=await packet();const stale=verifyReadingOutput(output(a.p),b.audit,codes);assert.ok(stale.errors.some(e=>e.code==='RECEIPT_MISMATCH'));const titles=verifyReadingOutput(output(a.p,{field:'title',excerpt:source.title}),a.audit,codes);assert.ok(titles.errors.some(e=>e.code==='AVAILABLE_TEXT_NOT_VERIFIED'));});
test('incorrect financial values, unknown stocks and uncovered citations fail',async()=>{const {p,audit}=await packet();const wrong=verifyReadingOutput(output(p,{fact:{label:'营业收入',value:'999.99',unit:'万元'}}),audit,codes);assert.ok(wrong.errors.some(e=>e.code==='FACT_NOT_IN_QUOTE'));assert.equal(verifyReadingOutput(output(p,{codes:['000001']}),audit,codes).gatePassed,false);const noQuote=verifyReadingOutput({evidenceIds:[source.id],readingReceipt:p.readingChallenge,readingChecks:[]},audit,codes);assert.ok(noQuote.errors.some(e=>e.code==='CITATION_WITHOUT_VERIFIED_QUOTE'));});
test('future documents fail independently and an empty as-of packet is explicitly not a reading proof',async()=>{const future=await packet({...source,availableAt:'2026-09-02T10:00:00+08:00'});assert.ok(verifyReadingOutput(output(future.p),future.audit,codes).errors.some(e=>e.code==='FUTURE_OR_UNDATED_DOCUMENT_SENT'));const p={asOf:'2026-09-01T15:00:00+08:00',documents:[]},audit=await prepareReadingPacket(p),result=verifyReadingOutput({evidenceIds:[]},audit,codes);assert.equal(result.status,'no_visible_documents');assert.equal(result.gatePassed,true);assert.equal(result.counts.verifiedTextExcerpts,0);});
test('old evidence IDs do not retroactively become verified-reading records',()=>{const state={config:{mode:'ai'},decisions:[{date:'2026-09-01',evidenceIds:[source.id],retrieval:{returnedDocuments:1}}]};const summary=summarizeRunReading(state);assert.equal(summary.totalDecisions,1);assert.equal(summary.legacyUnverified,1);assert.equal(summary.verifiedTextDecisions,0);assert.equal(summary.understandingVerified,false);});
test('model call stores the actual request hash, verified excerpt and immutable idempotent result',async()=>{const DB=database(),d=dataset(),state=newRun(d,{ruleMode:'research_assumptions',acknowledgeUnverifiedRules:true});let calls=0,body;try{const fetcher=async(url,options)=>{calls++;body=options.body;const p=JSON.parse(JSON.parse(body).messages[1].content);return Response.json({id:'TEST_PROVIDER_RESPONSE',model:'TEST_MODEL',choices:[{finish_reason:'stop',message:{content:JSON.stringify({...output(p),allocationScores:{'600519':100},investedFraction:.8,reason:'SYNTHETIC verified decision'})}}],usage:{prompt_tokens:10,completion_tokens:20,total_tokens:30}});};const env={SILICONFLOW_API_KEY:'TEST_ONLY_KEY'},config={provider:'siliconflow',model:'Qwen/Qwen3-8B',maxBudget:0};const result=await aiDecision(env,DB,'verified',0,state,d,'2026-09-01',config,fetcher);assert.equal(result.readingAudit.requestHash,await sha256(body));assert.equal(result.readingAudit.delivery,'provider_response_received');assert.equal(result.readingAudit.providerRequestId,'TEST_PROVIDER_RESPONSE');assert.equal(result.readingAudit.status,'text_excerpt_verified');assert.equal(result.readingAudit.mode,'enforce');const saved=JSON.parse(DB.prepare('SELECT payload FROM model_attempts WHERE id=?').bind('verified:0').first().payload);assert.equal(saved.readingAudit.documents[0].text,source.text);assert.ok(!JSON.stringify(saved).includes('TEST_ONLY_KEY'));assert.deepEqual(await aiDecision(env,DB,'verified',0,state,d,'2026-09-01',config,fetcher),result);assert.equal(calls,1);}finally{DB.close();}});
test('API rejects a fabricated reading proof before persisting a decision or placing a pending trade',async()=>{const DB=database(),d=dataset(),state=newRun(d,{ruleMode:'research_assumptions',acknowledgeUnverifiedRules:true});state.config.mode='ai';state.config.model={provider:'siliconflow',model:'Qwen/Qwen3-8B',maxBudget:0};DB.prepare('INSERT INTO datasets VALUES(?,?,?)').bind('d','now',JSON.stringify(d)).run();DB.prepare('INSERT INTO runs VALUES(?,?,0,?,?,?)').bind('r','d','now','now',JSON.stringify(state)).run();const original=globalThis.fetch;let calls=0;globalThis.fetch=async(url,options)=>{calls++;const p=JSON.parse(JSON.parse(options.body).messages[1].content);return Response.json({choices:[{finish_reason:'stop',message:{content:JSON.stringify({...output(p,{excerpt:'营业收入为999.99万元，同比增长99.9%。'}),weights:{'600519':1},reason:'SYNTHETIC fabricated proof'})}}]});};try{const response=await worker.fetch(new Request('https://local.test/api/runs/r/step',{method:'POST',body:JSON.stringify({expectedVersion:0})}),{DB,SILICONFLOW_API_KEY:'TEST_ONLY_KEY'});assert.equal(response.status,400);assert.match((await response.json()).error,/READING_VERIFICATION_FAILED/);const row=DB.prepare('SELECT version,payload FROM runs WHERE id=?').bind('r').first(),saved=JSON.parse(row.payload);assert.equal(row.version,0);assert.equal(saved.decisions.length,0);assert.equal(saved.pending,null);const attempt=DB.prepare('SELECT status,payload FROM model_attempts WHERE id=?').bind('r:0').first();assert.equal(attempt.status,'uncertain');assert.ok(JSON.parse(attempt.payload).readingAudit.errors.some(e=>e.code==='QUOTE_NOT_IN_SENT_CONTENT'));const read=await(await worker.fetch(new Request('https://local.test/api/runs/r/reading-audit'),{DB})).json();assert.equal(read.currentAttempt.readingAudit.status,'failed');assert.equal(calls,1);}finally{globalThis.fetch=original;DB.close();}});
