import {validateDataset,validDate} from './engine.js';
import {classifyAshare} from './catalogue.js';
const delay=ms=>new Promise(r=>setTimeout(r,ms));
export async function collectAnnouncements(stock,start,end,{maxPages=5,reader=readPublic,wait=delay}={}){
 const documents=new Map(),sources=[];let pagesRead=0,hasMore=true,total=null,error=null;
 for(let page=1;page<=maxPages&&hasMore;page++){
  if(page>1)await wait(2000);
  const parameters={pageNum:String(page),pageSize:'30',column:stock.exchange==='SSE'?'sse':stock.exchange==='BSE'?'bse':'szse',tabName:'fulltext',plate:stock.exchange==='SSE'?'sh':stock.exchange==='BSE'?'bj':'sz',searchkey:'',stock:stock.code+','+stock.orgId,secid:'',category:'',trade:'',seDate:start+'~'+end,sortName:'time',sortType:'asc',isHLtitle:'false'};
  try{const response=await reader('https://www.cninfo.com.cn/new/hisAnnouncement/query',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(parameters).toString()});
  const data=response.json;if(!data||data.announcements!==null&&!Array.isArray(data.announcements)||typeof data.hasMore!=='boolean')throw Error('公告索引格式变化，未当作没有公告');
  sources.push({...response.provenance,kind:'公告索引',code:stock.code,parameters});pagesRead++;hasMore=data.hasMore;total=data.totalAnnouncement??total;
  const records=(data.announcements||[]).filter(x=>x.secCode===stock.code);
  if(!records.length&&hasMore)throw Error('公告来源有后续页但本页为空，停止避免重复翻页');
  for(const item of records){
   if(!Number.isFinite(item.announcementTime)||!/^finalpage\//.test(item.adjunctUrl||''))continue;
   const publicationDate=new Date(item.announcementTime+8*3600000).toISOString().slice(0,10);
   if(publicationDate<start||publicationDate>end)continue;
   const following=new Date(Date.parse(publicationDate)+86400000).toISOString().slice(0,10);
   documents.set(String(item.announcementId),{id:String(item.announcementId),code:stock.code,title:String(item.announcementTitle).replace(/<[^>]*>/g,''),publicationDate,availableAt:following+'T00:00:00+08:00',timestampPrecision:'date_only_conservative_next_day',url:'https://static.cninfo.com.cn/'+item.adjunctUrl,textStatus:'仅索引链接，未解析PDF',kind:'公司公告'});
  }
  }catch(e){error=String(e.message);hasMore=true;break;}
 }
 return {documents:[...documents.values()],sources,coverage:{code:stock.code,kind:'公司公告索引',start,end,status:error?'unavailable':'available',error,announcements:documents.size,pagesRead,sourceReportedTotal:total,queryExhausted:!hasMore,nextPage:hasMore?pagesRead+1:null,complete:!hasMore,note:error?'已保留'+documents.size+'条已获取公告，后续来源失败：'+error:hasMore?'已读取'+pagesRead+'页，来源尚有更多公告，覆盖不完整':'本次来源查询已遍历，索引不等同PDF正文或不可变历史档案'}};
}
export async function sha256(s){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))].map(x=>x.toString(16).padStart(2,'0')).join('');}
export async function readPublic(url,options={}){const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),20000);try{const response=await fetch(url,{...options,signal:controller.signal,headers:{'User-Agent':'AshareReplayResearch/1.0','Accept':'application/json',...options.headers}});if(!response.ok)throw Error('来源返回 HTTP '+response.status+'；已停止，不绕过限制');if(Number(response.headers.get('content-length'))>3000000){await response.body?.cancel();throw Error('来源数据超过大小限制');}let raw='',bytes=0;const reader=response.body?.getReader(),decoder=new TextDecoder();if(reader)try{while(true){const {done,value}=await reader.read();if(done)break;bytes+=value.byteLength;if(bytes>3000000){await reader.cancel();throw Error('来源数据超过大小限制');}raw+=decoder.decode(value,{stream:true});}raw+=decoder.decode();}finally{reader.releaseLock();}let json;try{let payload=raw;if(raw.startsWith('researchCallback('))payload=raw.trim().slice(17,-1);if(url.startsWith('https://q.stock.sohu.com/')){const m=raw.match(/^historySearchHandler\((\[[\s\S]*\])\)\s*$/);if(!m)throw Error('行情格式不可解析');payload=m[1];}if(url.startsWith('https://quotes.sina.cn/')){const m=raw.match(/var research=\((\[[\s\S]*\])\);?\s*$/);if(!m)throw Error('行情格式不可解析');payload=m[1];}json=JSON.parse(payload);}catch{throw Error('来源未返回 JSON，可能访问受限；已停止');}return {json,provenance:{url,fetchedAt:new Date().toISOString(),sha256:await sha256(raw),access:'公开无密钥；不代表开放再分发许可'}};}finally{clearTimeout(timeout);}}
export async function collectDataset(input,catalogue){const start=input.start,end=input.end,codes=input.codes;const contextDays=input.documentContextDays||0;if(!Number.isInteger(contextDays)||contextDays<0||contextDays>90)throw Error('背景资料天数须为0至90');const documentContextStart=contextDays?new Date(Date.parse(start)-contextDays*86400000).toISOString().slice(0,10):start;if(!validDate(start)||!validDate(end)||start>end||(Date.parse(end)-Date.parse(start))/86400000>90)throw Error('单次来源请求最多90自然日；大范围请使用可恢复任务');if(end>=new Date(Date.now()+8*3600000).toISOString().slice(0,10))throw Error('结束日期必须早于今天，避免使用未收盘日线');if(!Array.isArray(codes)||!codes.length||new Set(codes).size!==codes.length||codes.some(c=>!catalogue.stocks.some(s=>s.code===c)))throw Error('内部采集批次必须是单只股票；大范围请使用可恢复任务');let stocks=[],documents=[],sources=[],warnings=['这是未复权价格回测，不是含分红再投资的总收益回测','未提供完整企业行动、历史 ST 状态和停复牌日历；异常跳变会暂停模拟','新闻为有界搜索摘要，不是完整历史档案；公告正文需通过文本导入补充','成交量单位未独立核实，仅用于判断零成交，不估计市场冲击容量'],coverage=[],unavailable=[];
for(const code of codes){const s=catalogue.stocks.find(x=>x.code===code);try{let pre=new Date(Date.parse(start)-40*86400000).toISOString().slice(0,10);let url,rawBars,provenance;if(s.exchange==='BSE'){if(start<'2025-10-09')throw Error('北交所2025-10-09代码切换之前需导入有日期身份映射的历史行情，不自动拼接新旧代码');const from=new Date(Date.parse(start)-10*86400000).toISOString().slice(0,10);url='https://q.stock.sohu.com/hisHq?'+new URLSearchParams({code:'cn_'+s.code,start:from.replaceAll('-',''),end:end.replaceAll('-',''),stat:'0',order:'D',period:'d',callback:'historySearchHandler',rt:'jsonp'});let response=await readPublic(url);provenance=response.provenance;let data=response.json?.[0];if(data?.status!==0||!Array.isArray(data.hq)||data.hq.length>=100)throw Error('北交所行情不足或达到来源100条限制');rawBars=data.hq.map(row=>({date:row[0],open:+row[1],close:+row[2],high:+row[6],low:+row[5],volume:+row[7]})).sort((a,b)=>a.date.localeCompare(b.date));warnings.push(s.name+' 使用搜狐未复权日线，成交量为来源手数（可能取整）；北交所旧代码不自动拼接');}else{url='https://web.ifzq.gtimg.cn/appstock/app/fqkline/get?param='+s.symbol+',day,'+pre+','+end+',150,';let response=await readPublic(url);provenance=response.provenance;if(response.json.code!==0)throw Error(s.name+' 行情源拒绝查询');let rows=response.json.data?.[s.symbol]?.day;if(!Array.isArray(rows)||rows.length<1||rows.length>=150)throw Error(s.name+' 行情不足或可能被截断');rawBars=rows.map(row=>({date:row[0],open:+row[1],close:+row[2],high:+row[3],low:+row[4],volume:+row[5]}));}let bars=rawBars.filter(b=>b.date>=pre&&b.date<=end);if(bars.filter(b=>b.date>=start).length<1)throw Error('该采集区间未返回日线，可能为休市、停牌或数据缺口；未用虚构数据补齐');validateDataset({start,end,stocks:[{...s,bars}],sources:[],documents:[]});stocks.push({...s,bars,ruleEvidence:[],eligibility:{status:'needs_verification',reason:'需导入该时段交易状态证据（普通交易、上市特殊期及历史ST）；仍可浏览行情和资料'}});sources.push({...provenance,kind:'未复权日线',code,fields:s.exchange==='BSE'?'搜狐hq未复权日线；成交量手数仅判断零值，不推算容量；不拼接旧代码':'仅 day 数组；今日 qt 等元数据全部排除',first:bars[0]?.date,last:bars.at(-1)?.date});await delay(1500);
try{const a=await collectAnnouncements(s,documentContextStart,end,{maxPages:input.announcementPages||5});documents.push(...a.documents);sources.push(...a.sources);coverage.push(a.coverage);if(!a.coverage.complete)warnings.push(s.name+' '+a.coverage.note);}catch(e){coverage.push({code,kind:'公司公告索引',announcements:0,complete:false,status:'unavailable',note:String(e.message)});warnings.push(s.name+' 公告暂不可用：'+e.message);}await delay(1500);
if(input.legacyNews===true)try{let params={uid:'',keyword:code,type:['cmsArticleWebOld'],client:'web',clientType:'web',clientVersion:'curr',param:{cmsArticleWebOld:{searchScope:'default',sort:'time',pageIndex:1,pageSize:30,preTag:'',postTag:''}}};let n=await readPublic('https://search-api-web.eastmoney.com/search/jsonp?'+new URLSearchParams({cb:'researchCallback',param:JSON.stringify(params)}));sources.push({...n.provenance,kind:'新闻搜索摘要',code});for(const x of n.json.result?.cmsArticleWebOld||[]){if(!/^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$/.test(x.date||'')||x.date.slice(0,10)<start||x.date.slice(0,10)>end||!/^https:\/\//.test(x.url||''))continue;documents.push({id:'news-'+x.code,code,title:String(x.title).replace(/<[^>]*>/g,''),publicationDate:x.date.slice(0,10),reportedAt:x.date.replace(' ','T')+'+08:00',availableAt:new Date(Math.max(Date.parse(n.provenance.fetchedAt),Date.parse(x.date.replace(' ','T')+'+08:00'))).toISOString(),firstObservedAt:n.provenance.fetchedAt,availabilityBasis:'observed_only',firstPublicationVerified:false,timestampPrecision:'retrieval_timestamp_not_historical_publication',url:x.url,text:String(x.content||'').replace(/<[^>]*>/g,''),textStatus:'搜索摘要，非完整文章；索引可能修订',kind:'新闻摘要'});}warnings.push(s.name+' 新闻仅查询最近 30 条并在本地过滤日期，不代表完整档案；可修订索引采用首次观察时间，不回填历史AI决策');}catch(e){warnings.push(s.name+' 新闻未获取：'+e.message);}else coverage.push({code,kind:'东方财富旧新闻搜索',status:'disabled',complete:false,note:'旧新闻接口返回406，不再自动请求；公司财经新闻由独立每经搜索适配器获取'});await delay(1500);}catch(e){unavailable.push({code,name:s.name,reason:String(e.message)});warnings.push(s.name+' 行情不可用：'+e.message);await delay(1500);}}
if(!stocks.length){const e=Error('所选股票行情均不可用：'+unavailable.map(x=>x.code+' '+x.reason).join('；'));e.unavailable=unavailable;throw e;}
const d={schemaVersion:2,requestedCodes:codes,unavailable,catalogueAsOf:catalogue.fetchedAt,start,end,...(contextDays?{documentContextStart}:{}),stocks,documents,sources,coverage,warnings,synthetic:false,collectedAt:new Date().toISOString(),newsCoverage:'incomplete_bounded_search_results',adjustment:'none',corporateActions:'not_complete'};d.corporateActions=[];if(stocks.some(s=>s.code==='601318')&&start<='2026-09-10'&&end>='2026-09-03')d.corporateActions.push({code:'601318',recordDate:'2026-09-09',exDate:'2026-09-10',payDate:'2026-09-10',cashPerShare:0.98,sourceUrl:'https://static.cninfo.com.cn/finalpage/2026-09-03/1225543317.PDF',taxAssumption:'gross'});d.warnings.push('已核验的现金分红按税前金额计入；其余企业行动可能缺失，非完整总收益');validateDataset(d);d.digest=await sha256(JSON.stringify({stocks,documents,start,end,corporateActions:d.corporateActions}));return d;}
