import {classifyAshare} from './catalogue.js';
import {validDate} from './engine.js';
export const CALENDAR_SOURCES=['https://www.sse.com.cn/disclosure/announcement/general/c/c_20251222_10802507.shtml','https://investor.szse.cn/disclosure/notice/general/t20251222_618087.html'];
export function calendarFor(start,end){const holidays=[['01-01','01-03'],['02-15','02-23'],['04-04','04-06'],['05-01','05-05'],['06-19','06-21'],['09-25','09-27'],['10-01','10-07']];let result=[];for(let t=Math.max(Date.parse(start),Date.parse('2026-01-01'));t<=Math.min(Date.parse(end),Date.parse('2026-12-31'));t+=86400000){let date=new Date(t).toISOString().slice(0,10),md=date.slice(5),day=new Date(t).getUTCDay();result.push({date,isOpen:day!==0&&day!==6&&!holidays.some(([a,b])=>md>=a&&md<=b),exchanges:['SSE','SZSE'],status:'announced_schedule',availableAt:'2025-12-23T00:00:00+08:00',sources:CALENDAR_SOURCES});}return result;}
export function parseFactors(raw,symbol){let text=raw.replace(/\/\*[\s\S]*?\*\//g,''),match=text.match(new RegExp('^\\s*var\\s+'+symbol+'hfq\\s*=\\s*(\\{[\\s\\S]*\\})\\s*;?\\s*$'));if(!match)throw Error('复权因子格式未识别');let data=JSON.parse(match[1]);if(!Array.isArray(data.data))throw Error('复权因子记录缺失');return data.data.map(x=>{if(!validDate(x.d)||!Number.isFinite(+x.f)||+x.f<=0)throw Error('复权因子字段无效');return {code:symbol.slice(2),effectiveDate:x.d,factor:+x.f,kind:'hfq',sentinel:x.d==='1900-01-01',pointInTimeVerified:false};});}
export function parseDividends(raw,code){let section=raw.split('分红方案(每10股)')[1]?.split('<!--配股 begin-->')[0];if(!section)throw Error('分红表格式未识别，未推断零分红');let out=[];for(const match of section.matchAll(/<tr\b[^>]*>([\s\S]*?)<\/tr>/gi)){let cells=[...match[1].matchAll(/<td\b[^>]*>([\s\S]*?)<\/td>/gi)].map(x=>x[1].replace(/<[^>]*>/g,'').replace(/&nbsp;|&#160;/g,' ').trim());if(cells.length<8||!/^\d{4}-\d{2}-\d{2}$/.test(cells[0]))continue;let date=x=>/^\d{4}-\d{2}-\d{2}$/.test(x)&&x!=='1900-01-01'?x:null,n=cells.slice(1,4).map(x=>Number((Number(x)/10).toFixed(10)));if(n.some(x=>!Number.isFinite(x)))throw Error('分红每10股字段不可解析');out.push({code,providerAnnouncementDate:date(cells[0]),bonusPerShare:n[0],capitalizationPerShare:n[1],grossCashPerShare:n[2],status:cells[4],exDate:date(cells[5]),recordDate:date(cells[6]),bonusListingDate:date(cells[7]),payDate:null,availableAt:null,pointInTimeVerified:false});}return out;}
async function publicText(url,encoding='utf-8'){await new Promise(r=>setTimeout(r,2000));let controller=new AbortController(),timer=setTimeout(()=>controller.abort(),20000);try{let res=await fetch(url,{signal:controller.signal,headers:{'User-Agent':'AshareReplayResearch/1.0'}});if(!res.ok)throw Error('来源HTTP '+res.status+'；停止，不绕过限制');let bytes=await res.arrayBuffer();if(bytes.byteLength>2000000)throw Error('来源响应超过单请求读取预算');return {raw:new TextDecoder(encoding).decode(bytes),provenance:{url,fetchedAt:new Date().toISOString(),sha256:[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(x=>x.toString(16).padStart(2,'0')).join(''),availability:'public_no_key_not_redistribution_license'}};}finally{clearTimeout(timer);}}
export async function cachedSupport(db,key,fetcher){let row=await db.prepare('SELECT payload FROM settings WHERE id=?').bind('daily:'+key).first();if(row)return JSON.parse(row.payload);let result;try{result=await fetcher();}catch(e){result={unavailable:String(e.message),fetchedAt:new Date().toISOString()};}await db.prepare('INSERT INTO settings(id,payload) VALUES(?,?) ON CONFLICT(id) DO UPDATE SET payload=excluded.payload').bind('daily:'+key,JSON.stringify(result)).run();return result;}
export async function collectDailySupport(db,d){const calendar=calendarFor(d.start,d.end),asOf=new Date().toISOString().slice(0,10),coverage=[{kind:'交易日历',status:'partial',note:'仅2026沪深官方公告日历；不覆盖北交所、其他年份或后续临时休市。缺行情不等于停牌。'}],factors=[],events=[],sources=[];let benchmark=await cachedSupport(db,'benchmark:'+d.start+':'+d.end,async()=>{let url='https://web.ifzq.gtimg.cn/appstock/app/fqkline/get?param=sh000300,day,'+d.start+','+d.end+',100,',r=await publicText(url),j=JSON.parse(r.raw),rows=j.data?.sh000300?.day;if(j.code!==0||!Array.isArray(rows)||rows.length>=100||!rows.length)throw Error('基准行情为空或达到来源截断限制');let bars=rows.filter(x=>x[0]>=d.start&&x[0]<=d.end).map(x=>({date:x[0],close:+x[2]}));if(bars.some(x=>!validDate(x.date)||!Number.isFinite(x.close)||x.close<=0))throw Error('基准行情字段无效');return {symbol:'sh000300',name:'沪深300',returnType:'price_index_not_total_return',bars,provenance:r.provenance};});coverage.push({kind:'基准指数',status:benchmark.unavailable?'unavailable':'available',note:benchmark.unavailable||'沪深300价格指数，非全收益、非可直接成交证券'});if(benchmark.provenance)sources.push({...benchmark.provenance,kind:'沪深300价格指数'});
for(const s of d.stocks){if(classifyAshare(s.code)?.exchange==='BSE'){coverage.push({code:s.code,kind:'企业行动/因子',status:'unverified',note:'北交所适配未核验，不推断无企业行动'});continue;}let factor=await cachedSupport(db,'factor:'+s.symbol+':'+asOf,async()=>{let r=await publicText('https://finance.sina.com.cn/realstock/company/'+s.symbol+'/hfq.js');return {records:parseFactors(r.raw,s.symbol),provenance:r.provenance};});let dividends=await cachedSupport(db,'dividend:'+s.code+':'+asOf,async()=>{let r=await publicText('https://vip.stock.finance.sina.com.cn/corp/go.php/vISSUE_ShareBonus/stockid/'+s.code+'.phtml','gb18030');return {records:parseDividends(r.raw,s.code),provenance:r.provenance};});for(const [kind,data,output] of [['复权因子',factor,factors],['分红/送转记录',dividends,events]]){coverage.push({code:s.code,kind,status:data.unavailable?'unavailable':'diagnostic_only',note:data.unavailable||'今日检索，非历史时点快照；不自动改变成交价或现金账'});if(data.provenance){sources.push({...data.provenance,code:s.code,kind});output.push(...data.records.map(x=>({...x,sourceUrl:data.provenance.url,fetchedAt:data.provenance.fetchedAt})));}}}
return {calendar,benchmark:benchmark.unavailable?null:benchmark,factors,events,coverage,sources};}
export function benchmarkReturn(d,date){let rows=(d.dailySupport?.benchmark?.bars||[]).filter(x=>x.date>=d.start&&x.date<=date);if(rows.length<2)return null;return {value:rows.at(-1).close/rows[0].close-1,firstDate:rows[0].date,lastDate:rows.at(-1).date,returnType:'price_index_not_total_return'};}
