export const UNIVERSE=[{code:'600519',name:'贵州茅台',symbol:'sh600519'},{code:'600036',name:'招商银行',symbol:'sh600036'},{code:'601318',name:'中国平安',symbol:'sh601318'}];
export const cutoffFor=date=>date+'T15:00:00+08:00';
export function visibleDocuments(docs,date){let cutoff=Date.parse(cutoffFor(date));return docs.filter(d=>Number.isFinite(Date.parse(d.availableAt))&&Date.parse(d.availableAt)<=cutoff).sort((a,b)=>Date.parse(b.availableAt)-Date.parse(a.availableAt));}
export function validDate(s){return typeof s==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(s)&&new Date(s).toISOString().slice(0,10)===s;}
export function validateDataset(d){if(!d||!Array.isArray(d.stocks)||!d.stocks.length||d.stocks.length>3)throw Error('请选择 1–3 只支持的股票');if(new Set(d.stocks.map(s=>s.code)).size!==d.stocks.length)throw Error('股票代码不可重复');if(!validDate(d.start)||!validDate(d.end)||d.start>d.end)throw Error('日期范围无效');if((Date.parse(d.end)-Date.parse(d.start))/86400000>120)throw Error('首版单次最多 120 个自然日');for(const s of d.stocks){if(!UNIVERSE.some(x=>x.code===s.code))throw Error('首版只支持列表中的沪市主板股票');if(!Array.isArray(s.bars)||s.bars.length<2)throw Error(s.code+' 的真实行情不足');let prev='';for(const b of s.bars){if(!validDate(b.date)||b.date<=prev)throw Error('行情日期重复或未排序');prev=b.date;for(const k of ['open','high','low','close'])if(!Number.isFinite(b[k])||b[k]<=0)throw Error('无效行情价格');if(b.high<Math.max(b.open,b.close)||b.low>Math.min(b.open,b.close)||b.high<b.low||!Number.isFinite(b.volume)||b.volume<0)throw Error('OHLC 或成交量不合法');}}
if(!Array.isArray(d.sources)||d.sources.some(s=>!/^https:\/\//.test(s.url||'')))throw Error('数据集来源必须是 HTTPS 链接');if(!Array.isArray(d.documents))d.documents=[];if(!Array.isArray(d.corporateActions))d.corporateActions=[];if(new Set(d.corporateActions.map(a=>a.code+':'+a.exDate)).size!==d.corporateActions.length)throw Error('企业行动不可重复');for(const a of d.corporateActions){if(!UNIVERSE.some(s=>s.code===a.code)||!validDate(a.recordDate)||!validDate(a.exDate)||!validDate(a.payDate)||a.exDate<=a.recordDate||a.payDate<a.exDate||!Number.isFinite(a.cashPerShare)||a.cashPerShare<=0||!/^https:\/\//.test(a.sourceUrl||''))throw Error('企业行动字段无效');}for(const x of d.documents){if(typeof x.id!=='string'||!x.id||x.id.length>200||typeof x.title!=='string'||!x.title||x.title.length>2000||!/(Z|[+-]\d{2}:\d{2})$/.test(x.availableAt||'')||(x.text!==undefined&&(typeof x.text!=='string'||x.text.length>500000))||!/^https:\/\//.test(x.url||'')||!Number.isFinite(Date.parse(x.availableAt)))throw Error('文档缺少来源或可靠公开时间');}return d;}
export function newRun(d,config){validateDataset(d);const n=(x,min,max,name)=>{x=Number(x);if(!Number.isFinite(x)||x<min||x>max)throw Error(name+'超出范围');return x;};if(config.mode==='ai')throw Error('AI API 尚未配置，不能生成 AI 决策');const days=[...new Set(d.stocks.flatMap(s=>s.bars.map(b=>b.date)))].filter(t=>t>=d.start&&t<=d.end).sort();if(days.length<2)throw Error('至少需要两个交易日');let c={mode:'baseline',strategy:config.strategy==='hold'?'hold':'equal',initial:n(config.initial??1000000,10000,100000000,'初始资金'),frequency:Math.round(n(config.frequency??5,1,30,'调仓间隔')),commissionBps:n(config.commissionBps??3,0,100,'佣金'),minCommission:n(config.minCommission??5,0,100,'最低佣金'),stampBps:n(config.stampBps??5,0,100,'卖出印花税'),transferBps:n(config.transferBps??0.1,0,10,'过户费'),slippageBps:n(config.slippageBps??5,0,100,'滑点')};return {config:c,days,index:-1,cash:c.initial,positions:Object.fromEntries(d.stocks.map(s=>[s.code,{qty:0,boughtOn:null}])),pending:null,entitlements:{},paidDividends:[],dividendIncome:0,curve:[],trades:[],decisions:[],logs:[],fees:0,turnover:0,status:'ready',warnings:d.warnings||[],synthetic:!!d.synthetic};}
export function stepRun(old,d){const r=structuredClone(old);if(r.index>=r.days.length-1)return r;let i=r.index+1,date=r.days[i],bars=Object.fromEntries(d.stocks.map(s=>[s.code,s.bars.find(b=>b.date===date)]));const log=(code,text)=>r.logs.push({date,code,text});
const actions=d.corporateActions||[];
// Conservative corporate-action discontinuity guard. This is a heuristic, not corporate-action coverage.
for(const s of d.stocks){let b=bars[s.code],p=s.bars.filter(x=>x.date<date).at(-1);if(b&&p&&Math.abs(b.open/(p.close-actions.filter(a=>a.code===s.code&&a.exDate===date).reduce((v,a)=>v+a.cashPerShare,0))-1)>.105){r.status='blocked';log(s.code,'开盘跳变超过主板常规涨跌幅：可能除权、数据异常或特殊交易日，需核验企业行动后重建数据集');return r;}}
for(const a of actions){let key=a.code+':'+a.exDate;if(a.payDate<=date&&!r.paidDividends.includes(key)){let qty=r.entitlements[key]||0,amount=qty*a.cashPerShare;r.cash+=amount;r.dividendIncome+=amount;r.paidDividends.push(key);if(amount)log(a.code,'已计入已核验税前现金分红 '+amount.toFixed(2)+' 元；未扣个人差异化红利税');}}
if(r.pending){let equity=r.pending.equity;let target={};for(const s of d.stocks){let b=bars[s.code];target[s.code]=b?Math.floor(equity*r.pending.weights[s.code]/b.open/100)*100:r.positions[s.code].qty;}
const trade=(s,side,qty)=>{let b=bars[s.code],p=s.bars.filter(x=>x.date<date).at(-1),pos=r.positions[s.code];if(!b||b.volume<=0){log(s.code,'停牌或缺少当日行情：不成交');return;}if(!p){log(s.code,'缺少前收盘价：不成交');return;}let reference=p.close-actions.filter(a=>a.code===s.code&&a.exDate===date).reduce((v,a)=>v+a.cashPerShare,0);let up=Math.round(reference*1.1*100)/100,down=Math.round(reference*.9*100)/100;if((side==='buy'&&b.open>=up-.005)||(side==='sell'&&b.open<=down+.005)){log(s.code,'开盘触及涨跌停，缺少盘口证据：保守不成交');return;}if(side==='sell'&&pos.boughtOn===date){log(s.code,'T+1：当日买入不可卖出');return;}let rawPrice=b.open*(1+(side==='buy'?1:-1)*r.config.slippageBps/10000);let price=+Math.max(b.low,down,Math.min(b.high,up,rawPrice)).toFixed(2);let fee=q=>Math.max(r.config.minCommission,q*price*r.config.commissionBps/10000)+q*price*(r.config.transferBps+(side==='sell'?r.config.stampBps:0))/10000;
if(side==='buy'){qty=Math.floor(qty/100)*100;while(qty>0&&qty*price+fee(qty)>r.cash+1e-7)qty-=100;}else qty=Math.min(qty,pos.qty);if(qty<=0){if(side==='buy')log(s.code,'资金或整手约束：不成交');return;}let fees=fee(qty);r.cash+=(side==='buy'?-qty*price:qty*price)-fees;pos.qty+=side==='buy'?qty:-qty;if(side==='buy')pos.boughtOn=date;r.fees+=fees;r.turnover+=qty*price;r.trades.push({date,code:s.code,side,qty,price,fees:+fees.toFixed(2),signalDate:r.pending.date});};
for(const s of d.stocks)if(r.positions[s.code].qty>target[s.code])trade(s,'sell',r.positions[s.code].qty-target[s.code]);for(const s of d.stocks)if(r.positions[s.code].qty<target[s.code])trade(s,'buy',target[s.code]-r.positions[s.code].qty);r.pending=null;}
for(const a of actions)if(a.recordDate===date)r.entitlements[a.code+':'+a.exDate]=r.positions[a.code]?.qty||0;
let equity=r.cash;for(const a of actions)if(a.exDate<=date&&a.payDate>date)equity+=(r.entitlements[a.code+':'+a.exDate]||0)*a.cashPerShare;for(const s of d.stocks){let b=s.bars.filter(b=>b.date<=date).at(-1);equity+=r.positions[s.code].qty*(b?.close||0);}let peak=Math.max(r.config.initial,...r.curve.map(x=>x.equity),equity);r.curve.push({date,equity:+equity.toFixed(2),cash:+r.cash.toFixed(2),drawdown:equity/peak-1});
if(i===0||(r.config.strategy==='equal'&&i%r.config.frequency===0)){let weights=Object.fromEntries(d.stocks.map(s=>[s.code,1/d.stocks.length]));r.pending={date,equity,weights};r.decisions.push({date,cutoff:cutoffFor(date),weights,evidenceIds:[],visibleDocuments:visibleDocuments(d.documents,date).length,reason:'固定规则等权配置，不读取新闻或财报，不是 AI 决策'});}
r.index=i;r.status=i===r.days.length-1?'completed':'running';return r;}
export function metrics(r){const c=r.curve;let equity=c.at(-1)?.equity??r.config.initial;let returns=c.slice(1).map((x,i)=>x.equity/c[i].equity-1);let avg=returns.reduce((a,b)=>a+b,0)/(returns.length||1),variance=returns.length>1?returns.reduce((a,b)=>a+(b-avg)**2,0)/(returns.length-1):0,vol=Math.sqrt(variance);return {equity,totalReturn:equity/r.config.initial-1,maxDrawdown:Math.min(0,...c.map(x=>x.drawdown)),volatility:returns.length>1?vol*Math.sqrt(252):null,sharpe:returns.length>1&&vol?avg/vol*Math.sqrt(252):null,fees:r.fees,turnover:r.turnover/r.config.initial,days:c.length};}
