const json=(v,status=200)=>new Response(JSON.stringify(v),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff'}});
async function body(request){const raw=await request.text();if(raw.length>1500000)throw Error('请求过大');try{return JSON.parse(raw);}catch{throw Error('无效 JSON');}}
const id=()=>crypto.randomUUID();
async function dataset(db,id){let row=await db.prepare('SELECT payload FROM datasets WHERE id=?').bind(id).first();if(!row)throw Error('数据集不存在');return JSON.parse(row.payload);}
async function runRow(db,id){let row=await db.prepare('SELECT * FROM runs WHERE id=?').bind(id).first();if(!row)throw Error('回测不存在');return row;}
function packRun(row){let state=JSON.parse(row.payload);return {id:row.id,datasetId:row.dataset_id,version:row.version,created:row.created,updated:row.updated,state,metrics:metrics(state)};}
export default {async fetch(request,env){let u=new URL(request.url);try{if(u.pathname==='/favicon.svg')return new Response('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="8" fill="#101c30"/><path d="M7 23V10m6 13V16m6 7V6m6 17V12" stroke="#5bd4d0" stroke-width="3"/></svg>',{headers:{'content-type':'image/svg+xml'}});if(u.pathname==='/')return new Response(PAGE,{headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff','content-security-policy':"default-src 'self'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; connect-src 'self'; img-src 'self' data:; frame-ancestors 'self' https://chatgpt.com"}});
if(!u.pathname.startsWith('/api/'))return json({error:'Not found'},404);if(!env.DB)return json({error:'数据库尚未就绪，请稍后再试'},503);
// Private Sites dispatch enforces owner-only authentication; browser mutation requests must be same-origin.
if(request.method!=='GET'&&request.headers.get('Origin')&&request.headers.get('Origin')!==u.origin)return json({error:'跨站写入已拒绝'},403);
if(u.pathname==='/api/test-free-model'&&request.method==='POST'){let input=await body(request);return json(await testSiliconFlow(input.sessionKey,input.model));}
if(u.pathname==='/api/model-config'){if(request.method==='GET'){let c=await env.DB.prepare('SELECT payload FROM settings WHERE id=?').bind('model').first(),config=c?JSON.parse(c.payload):{provider:'openai',model:'',maxBudget:1,inputPrice:0,outputPrice:0};return json({config,configured:!!(PROVIDERS[config.provider]&&env[PROVIDERS[config.provider].secret]&&config.model&&((config.inputPrice>0&&config.outputPrice>0)||(config.provider==='siliconflow'&&FREE_SILICONFLOW_MODELS.includes(config.model)))),inferenceImplemented:true,reason:'密钥仅保存在服务器；没有密钥时不会调用模型'});}let c=await body(request);if(Object.keys(c).some(k=>!['provider','model','maxBudget','inputPrice','outputPrice'].includes(k)))throw Error('不接收密钥或未知字段');if(!['openai','deepseek','qwen','siliconflow'].includes(c.provider)||typeof c.model!=='string'||c.model.length>100||!Number.isFinite(c.maxBudget)||c.maxBudget<0||c.maxBudget>1000||!Number.isFinite(c.inputPrice)||c.inputPrice<0||c.inputPrice>1000||!Number.isFinite(c.outputPrice)||c.outputPrice<0||c.outputPrice>1000)throw Error('模型配置无效');await env.DB.prepare('INSERT INTO settings(id,payload) VALUES(?,?) ON CONFLICT(id) DO UPDATE SET payload=excluded.payload').bind('model',JSON.stringify(c)).run();return json({config:c,configured:false,inferenceImplemented:true});}
if(u.pathname==='/api/import'&&request.method==='POST'){let d=validateDataset(await body(request));if(d.synthetic)throw Error('生产界面不接受合成数据');d.warnings=Array.isArray(d.warnings)?d.warnings:[];d.coverage=Array.isArray(d.coverage)?d.coverage:[];d.importedAt=new Date().toISOString();d.digest=await sha256(JSON.stringify(d));let did=id();await env.DB.prepare('INSERT INTO datasets(id,created,payload) VALUES(?,?,?)').bind(did,d.importedAt,JSON.stringify(d)).run();return json({id:did,dataset:d,cached:false});}
if(u.pathname==='/api/status')return json({ai:{configured:false,reason:'API 预留，未配置任何模型或密钥'},universe:UNIVERSE,engineVersion:'1.0.0',storage:'D1',news:'bounded_search_excerpts'});
if(u.pathname==='/api/datasets'&&request.method==='GET'){let rows=await env.DB.prepare('SELECT id,created,payload FROM datasets ORDER BY created DESC LIMIT 20').all();return json(rows.results.map(x=>{let d=JSON.parse(x.payload);return{id:x.id,created:x.created,start:d.start,end:d.end,stocks:d.stocks.map(s=>({code:s.code,name:s.name})),digest:d.digest};}));}
if(u.pathname==='/api/collect'&&request.method==='POST'){let input=await body(request),existing=await env.DB.prepare('SELECT id,payload FROM datasets ORDER BY created DESC LIMIT 20').all();let hit=existing.results.find(x=>{let d=JSON.parse(x.payload);return d.start===input.start&&d.end===input.end&&d.stocks.map(s=>s.code).sort().join(',')===(input.codes||[]).slice().sort().join(',');});if(hit)return json({id:hit.id,dataset:JSON.parse(hit.payload),cached:true});let logId=id();try{let d=await collectDataset(input),did=id(),now=new Date().toISOString();await env.DB.batch([env.DB.prepare('INSERT INTO datasets(id,created,payload) VALUES(?,?,?)').bind(did,now,JSON.stringify(d)),env.DB.prepare('INSERT INTO fetch_logs(id,created,payload) VALUES(?,?,?)').bind(logId,now,JSON.stringify({status:'success',datasetId:did,sources:d.sources.length,warnings:d.warnings}))]);return json({id:did,dataset:d,cached:false});}catch(e){await env.DB.prepare('INSERT INTO fetch_logs(id,created,payload) VALUES(?,?,?)').bind(logId,new Date().toISOString(),JSON.stringify({status:'failed',message:e.message})).run();throw e;}}
let match=u.pathname.match(/^\/api\/datasets\/([^/]+)$/);if(match)return json(await dataset(env.DB,match[1]));
if(u.pathname==='/api/runs'&&request.method==='GET'){let rows=await env.DB.prepare('SELECT * FROM runs ORDER BY created DESC LIMIT 20').all();return json(rows.results.map(packRun));}
if(u.pathname==='/api/runs'&&request.method==='POST'){let input=await body(request);if(!input.acknowledgeLimitations)throw Error('请确认数据缺口与价格回测限制');let d=await dataset(env.DB,input.datasetId),wantAI=input.config?.strategy==='ai'||input.config?.mode==='ai',state=newRun(d,{...(input.config||{}),mode:'baseline'}),rid=id(),now=new Date().toISOString();if(wantAI){let m=await env.DB.prepare('SELECT payload FROM settings WHERE id=?').bind('model').first();let config=m?JSON.parse(m.payload):null;if(!config||!PROVIDERS[config.provider]||!(env[PROVIDERS[config.provider].secret]||(config.provider==='siliconflow'&&typeof input.sessionKey==='string'&&input.sessionKey.length>=8))||!config.model||(!(config.inputPrice>0&&config.outputPrice>0)&&!(config.provider==='siliconflow'&&FREE_SILICONFLOW_MODELS.includes(config.model))))throw Error('AI 未配置：需要服务器密钥、模型与已核实的计费单价');state.config.mode='ai';state.config.model=config;}await env.DB.prepare('INSERT INTO runs(id,dataset_id,version,created,updated,payload) VALUES(?,?,0,?,?,?)').bind(rid,input.datasetId,now,now,JSON.stringify(state)).run();return json(packRun(await runRow(env.DB,rid)));}
match=u.pathname.match(/^\/api\/runs\/([^/]+)(?:\/(step|snapshot|export))?$/);if(match){let row=await runRow(env.DB,match[1]);if(match[2]==='step'&&request.method==='POST'){let input=await body(request);if(!Number.isInteger(input.expectedVersion)||input.expectedVersion<0)throw Error('缺少有效版本号');if(row.version!==input.expectedVersion)return json({...packRun(row),replayed:true});let d=await dataset(env.DB,row.dataset_id),state=JSON.parse(row.payload);if(['completed','blocked'].includes(state.status))return json(packRun(row));let next=stepRun(state,d),now=new Date().toISOString();if(state.config.mode==='ai'&&next.status!=='blocked'&&next.status!=='completed'&&next.decisions.length>state.decisions.length){let date=next.days[next.index],result=await aiDecision(state.config.model.provider==='siliconflow'&&typeof input.sessionKey==='string'?{...env,SILICONFLOW_API_KEY:input.sessionKey}:env,env.DB,row.id,input.expectedVersion,next,d,date,state.config.model);next.pending.weights=result.decision.weights;next.decisions[next.decisions.length-1]={date,cutoff:cutoffFor(date),...result.decision,provider:result.provider,model:result.model,usage:result.usage,costUSD:result.costUSD};}await env.DB.prepare('UPDATE runs SET payload=?,version=version+1,updated=? WHERE id=? AND version=?').bind(JSON.stringify(next),now,row.id,input.expectedVersion).run();return json(packRun(await runRow(env.DB,row.id)));}if(match[2]==='snapshot'){let d=await dataset(env.DB,row.dataset_id),r=JSON.parse(row.payload);if(r.index<0)return json({date:null,documents:[],bars:[],note:'尚未开始，未释放任何行情或公告'});let date=r.days[r.index];return json({date,cutoff:cutoffFor(date),documents:visibleDocuments(d.documents,date),bars:d.stocks.map(s=>({...s,bars:s.bars.filter(b=>b.date<=date)})),coverage:d.coverage});}if(match[2]==='export'){let d=await dataset(env.DB,row.dataset_id);return new Response(JSON.stringify({app:'时点',engineVersion:'1.0.0',run:packRun(row),dataset:d,disclaimer:'模拟研究；固定规则基线，非 AI 投资建议；行情未复权，新闻缺失，公告正文未解析'},null,2),{headers:{'content-type':'application/json; charset=utf-8','content-disposition':'attachment; filename="ashare-run-'+row.id+'.json"','cache-control':'no-store'}});}return json(packRun(row));}
if(u.pathname==='/api/logs'){let x=await env.DB.prepare('SELECT * FROM fetch_logs ORDER BY created DESC LIMIT 20').all();return json(x.results.map(r=>({id:r.id,created:r.created,...JSON.parse(r.payload)})));}
return json({error:'接口不存在'},404);}catch(e){return json({error:String(e.message||e)},400);}}};
